from pathlib import Path
from bs4 import BeautifulSoup
import json, zipfile, re

BASE = Path('/mnt/data/ai-app-academy-column2-complete.html')
OUTDIR = Path('/mnt/data/ai-app-academy-varied-v3')
OUTDIR.mkdir(parents=True, exist_ok=True)

raw = BASE.read_text(encoding='utf-8')
soup = BeautifulSoup(raw, 'html.parser')

extra_css = r'''
/* =====================================================
   V3 varied interaction primitives — rewritten from scratch
   ===================================================== */
.artifact-ledger-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.artifact-card{min-height:126px;padding:14px;border:1px solid var(--line-strong);border-radius:11px;background:var(--card);box-shadow:2px 2px 0 rgba(21,32,43,.07)}.artifact-card.ready{border-color:var(--teal);background:var(--teal-soft)}.artifact-card span{color:var(--muted);font-family:var(--mono);font-size:10px;font-weight:800}.artifact-card b{display:block;margin:8px 0 4px}.artifact-card small{color:var(--muted)}
.v3-lab{overflow:hidden;border:1px solid var(--line-strong);border-radius:14px;background:var(--card);box-shadow:var(--shadow)}.v3-toolbar{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:13px 16px;border-bottom:1px solid var(--line);background:#f7f8f6}.v3-toolbar strong{font-family:var(--serif);font-size:17px}.v3-toolbar small{display:block;color:var(--muted)}.v3-actions{display:flex;gap:8px;flex-wrap:wrap}.v3-grid-2{display:grid;grid-template-columns:1fr 1fr;min-height:380px}.v3-pane{padding:18px}.v3-pane+.v3-pane{border-left:1px solid var(--line)}.v3-pane-title{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:12px}.v3-pane-title b{font-size:14px}.v3-pane-title span{color:var(--muted);font-family:var(--mono);font-size:10px}.v3-result{min-height:90px;margin-top:12px;padding:13px;border:1px solid var(--line);border-radius:10px;background:var(--paper);font-family:var(--mono);font-size:12px;white-space:pre-wrap}.v3-result.good{border-color:var(--teal);background:var(--teal-soft)}.v3-result.bad{border-color:var(--red);background:#fff1f2}.v3-metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;padding:14px;border-top:1px solid var(--line);background:#f7f8f6}.v3-metric{padding:10px;border:1px solid var(--line);border-radius:9px;background:#fff}.v3-metric span{display:block;color:var(--muted);font-size:10px}.v3-metric b{display:block;margin-top:3px;font-family:var(--mono)}
.code-repair-grid{display:grid;grid-template-columns:190px minmax(0,1fr) 280px;min-height:470px}.diagnostic-steps{padding:14px;border-right:1px solid var(--line);background:#f7f8f6}.diag-step{width:100%;display:grid;grid-template-columns:30px 1fr;gap:8px;align-items:start;padding:10px;margin-bottom:7px;border:1px solid var(--line);border-radius:9px;background:#fff;text-align:left}.diag-step.active{border-color:var(--teal);background:var(--teal-soft)}.diag-step.done{opacity:.72}.diag-step i{width:27px;height:27px;display:grid;place-items:center;border-radius:7px;background:var(--paper-deep);font-family:var(--mono);font-size:10px;font-style:normal}.diag-step b{font-size:12px}.diag-step small{display:block;color:var(--muted)}.editor-pane{display:flex;flex-direction:column;min-width:0}.editor-tabs{display:flex;gap:5px;padding:9px 10px;border-bottom:1px solid var(--line);background:#1d2832}.editor-tab{padding:6px 9px;border:0;border-radius:6px;background:transparent;color:#9fb0bb;font-family:var(--mono);font-size:11px}.editor-tab.active{background:#33424d;color:#fff}.code-editor{flex:1;min-height:320px;width:100%;resize:vertical;border:0;outline:0;padding:17px;background:#15202a;color:#e6eef2;font-family:var(--mono);font-size:12px;line-height:1.65;tab-size:2}.diagnostic-pane{padding:16px;border-left:1px solid var(--line)}.diagnostic-message{padding:12px;border:1px solid var(--line);border-radius:10px;background:var(--paper);font-size:12px}.diagnostic-message.bad{border-color:var(--red);background:#fff1f2}.diagnostic-message.good{border-color:var(--teal);background:var(--teal-soft)}.hint-box{margin-top:10px;padding:11px;border-left:4px solid var(--marker);background:#fffbea;font-size:12px}.test-log{margin-top:12px;padding:12px;border-radius:10px;background:#15202a;color:#dce8ec;font-family:var(--mono);font-size:11px;white-space:pre-wrap;min-height:120px}
.message-builder{display:grid;grid-template-columns:230px minmax(0,1fr);min-height:430px}.message-shelf{padding:14px;border-right:1px solid var(--line);background:#f7f8f6}.message-card{width:100%;display:block;margin-bottom:8px;padding:10px;border:1px solid var(--line);border-radius:9px;background:#fff;text-align:left}.message-card.selected{border-color:var(--teal);background:var(--teal-soft)}.message-card b{display:block;font-size:12px}.message-card small{color:var(--muted)}.window-stage{padding:18px}.token-ruler{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center}.token-bar{height:13px;overflow:hidden;border:1px solid var(--line);border-radius:99px;background:var(--paper-deep)}.token-used{height:100%;background:var(--teal);transition:.2s}.token-used.warn{background:var(--orange)}.context-window{display:flex;align-content:flex-start;gap:7px;flex-wrap:wrap;min-height:180px;margin-top:16px;padding:13px;border:1px dashed var(--line-strong);border-radius:11px;background:var(--paper)}.context-item{max-width:210px;padding:8px 10px;border:1px solid var(--line);border-radius:8px;background:#fff;font-size:11px}.context-item.system{border-color:#6f63a8}.context-item.user{border-color:var(--teal)}.context-item.history{border-color:#5b84b1}.context-item.document{border-color:#c88d35}.context-item.evicted{opacity:.28;text-decoration:line-through}.context-controls{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:14px}.context-controls label{font-size:11px;color:var(--muted)}
.routing-layout{display:grid;grid-template-columns:250px minmax(0,1fr);min-height:430px}.rule-panel{padding:15px;border-right:1px solid var(--line);background:#f7f8f6}.rule-row{display:grid;grid-template-columns:28px 1fr auto;gap:7px;align-items:center;margin-bottom:7px;padding:9px;border:1px solid var(--line);border-radius:9px;background:#fff}.rule-row b{font-size:11px}.rule-controls{display:flex;gap:3px}.rule-controls button{padding:3px 6px}.routing-stage{padding:17px;overflow:auto}.routing-table{width:100%;border-collapse:collapse;font-size:11px}.routing-table th,.routing-table td{padding:8px;border-bottom:1px solid var(--line);text-align:left}.routing-table .pass{color:var(--teal);font-weight:800}.routing-table .fail{color:var(--red);font-weight:800}.route-flow{display:flex;gap:7px;align-items:center;flex-wrap:wrap;margin:12px 0}.route-node{padding:7px 9px;border:1px solid var(--line);border-radius:8px;background:#fff;font-size:11px}.route-node.active{border-color:var(--teal);background:var(--teal-soft)}
.json-lab-grid{display:grid;grid-template-columns:230px minmax(0,1fr) 260px;min-height:430px}.json-presets{padding:14px;border-right:1px solid var(--line);background:#f7f8f6}.json-preset{width:100%;margin-bottom:7px;padding:10px;border:1px solid var(--line);border-radius:9px;background:#fff;text-align:left}.json-preset.active{border-color:var(--teal);background:var(--teal-soft)}.json-preset b{display:block;font-size:12px}.json-preset small{color:var(--muted)}.json-editor{width:100%;min-height:365px;resize:vertical;border:0;outline:0;padding:17px;background:#15202a;color:#e6eef2;font-family:var(--mono);font-size:12px;line-height:1.65}.gate-stack{padding:15px;border-left:1px solid var(--line)}.gate-box{margin-bottom:9px;padding:11px;border:1px solid var(--line);border-radius:9px;background:#fff}.gate-box.pass{border-color:var(--teal);background:var(--teal-soft)}.gate-box.fail{border-color:var(--red);background:#fff1f2}.gate-box b{display:block;font-size:12px}.gate-box small{color:var(--muted)}
.semantic-layout{display:grid;grid-template-columns:minmax(0,1fr) 260px;min-height:440px}.semantic-map{position:relative;min-height:440px;border-right:1px solid var(--line);background:radial-gradient(circle at center,rgba(11,122,117,.08),transparent 58%),var(--paper)}.semantic-axis-x,.semantic-axis-y{position:absolute;background:var(--line)}.semantic-axis-x{left:5%;right:5%;top:50%;height:1px}.semantic-axis-y{top:5%;bottom:5%;left:50%;width:1px}.semantic-point{position:absolute;transform:translate(-50%,-50%);max-width:130px;padding:7px 9px;border:1.5px solid var(--ink);border-radius:999px;background:#fff;font-size:10px;cursor:pointer;box-shadow:2px 2px 0 rgba(21,32,43,.08)}.semantic-point.query{background:var(--marker);font-weight:900}.semantic-point.selected{border-color:var(--teal);background:var(--teal);color:#fff}.semantic-point.boundary{border-style:dashed}.semantic-point.failure{border-radius:7px}.semantic-side{padding:15px}.budget-line{display:flex;justify-content:space-between;gap:10px;font-family:var(--mono);font-size:11px}.coverage-list{display:grid;gap:7px;margin-top:12px}.coverage-item{padding:9px;border:1px solid var(--line);border-radius:8px;background:#fff;font-size:11px}.coverage-item.pass{border-color:var(--teal);background:var(--teal-soft)}
.eval-controls{display:grid;grid-template-columns:minmax(0,1fr) 260px;min-height:390px}.prompt-editor-wrap{padding:15px}.prompt-editor{width:100%;min-height:235px;padding:14px;border:1px solid var(--line);border-radius:10px;background:#fff;font-family:var(--mono);font-size:12px;line-height:1.6;resize:vertical}.eval-side{padding:15px;border-left:1px solid var(--line);background:#f7f8f6}.eval-table-wrap{overflow:auto;border-top:1px solid var(--line)}.eval-table-v3{width:100%;border-collapse:collapse;font-size:10.5px}.eval-table-v3 th,.eval-table-v3 td{padding:8px;border-bottom:1px solid var(--line);text-align:left}.eval-table-v3 tr.regression{background:#fff1f2}.eval-table-v3 tr.fixed{background:var(--teal-soft)}.eval-filter.on{background:var(--teal);color:#fff}.golden-add{display:grid;grid-template-columns:1fr 150px auto;gap:7px;margin-top:10px}.golden-add input{min-width:0;padding:8px;border:1px solid var(--line);border-radius:8px}.dist-bars{display:grid;gap:8px}.dist-row{display:grid;grid-template-columns:90px 1fr 42px;gap:8px;align-items:center;font-size:11px}.dist-track{height:12px;background:var(--paper-deep);border-radius:99px;overflow:hidden}.dist-fill{height:100%;background:var(--teal);transition:.25s}.condition-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.condition-toggle{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:9px;border:1px solid var(--line);border-radius:9px;background:#fff;font-size:11px}.condition-toggle input{accent-color:var(--teal)}.counterfactual-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:7px}.counter-block{padding:10px;border:1px solid var(--line);border-radius:9px;background:#fff;text-align:center;font-size:10px}.counter-block.off{opacity:.35;text-decoration:line-through}.bridge-artifact{margin-top:18px;padding:13px;border:1px dashed var(--teal);border-radius:10px;background:var(--teal-soft);font-size:12px}.bridge-artifact b{color:var(--teal-dark)}
@media(max-width:930px){.code-repair-grid,.json-lab-grid{grid-template-columns:1fr}.diagnostic-steps,.json-presets{border-right:0;border-bottom:1px solid var(--line)}.diagnostic-pane,.gate-stack{border-left:0;border-top:1px solid var(--line)}.message-builder,.routing-layout,.semantic-layout,.eval-controls{grid-template-columns:1fr}.message-shelf,.rule-panel,.semantic-map{border-right:0;border-bottom:1px solid var(--line)}.eval-side{border-left:0;border-top:1px solid var(--line)}.artifact-ledger-grid{grid-template-columns:1fr 1fr}}
@media(max-width:620px){.v3-grid-2,.v3-metrics,.context-controls,.condition-grid,.counterfactual-grid{grid-template-columns:1fr}.v3-pane+.v3-pane{border-left:0;border-top:1px solid var(--line)}.artifact-ledger-grid{grid-template-columns:1fr}.golden-add{grid-template-columns:1fr}.semantic-map{min-height:500px}}
'''

# Append CSS
soup.style.string = (soup.style.string or '') + '\n' + extra_css

# Dashboard artifact ledger
ledger_html = '''
<section class="console-section" id="artifactLedger">
  <div class="console-section-head"><span class="chapter-no">04</span><h2>课程产物账本</h2><small>LIVE ARTIFACTS</small></div>
  <p class="console-section-lede">每一课不只打勾，还会留下下一课真正要用的产物。重做后的课程会把这些数据持续传下去。</p>
  <div class="artifact-ledger-grid" id="artifactLedgerGrid"></div>
</section>
'''
review = soup.find(id='review')
review.insert_before(BeautifulSoup(ledger_html, 'html.parser'))
# renumber review visually
head_no = review.find(class_='chapter-no')
if head_no: head_no.string = '05'
# fix review copy
p = review.find('p', class_='console-section-lede')
if p: p.string = '前两个专栏只覆盖模型调用和 Prompt 工程。新的课程产物会逐课保存，但 LangChain Agent、RAG、向量数据库、LangGraph 与 MCP API 仍保持锁定。'

# Enhancement blocks for lessons 1,2,5
l1 = soup.find(id='lesson1View')
l1_lab_ref = l1.find(id='labReflection')
l1_dist = BeautifulSoup('''
<div class="stage" id="l1DistributionLab">
  <span class="stage-tag">重复运行实验</span><h3>不要只看一次：让同一封邮件连续判断 20 次</h3>
  <p>业务规则影响分类稳定性；Schema 只影响返回格式，不会自动让分类更准确。切换两个开关，再运行观察。</p>
  <div class="v3-lab">
    <div class="v3-toolbar"><div><strong>20 次分类分布</strong><small>同一输入，同一模型，重复采样</small></div><div class="v3-actions"><label class="console-chip"><input id="l1DistRules" type="checkbox"> 加入业务规则</label><label class="console-chip"><input id="l1DistSchema" type="checkbox"> 固定 JSON</label><button class="button primary" id="l1DistRun" type="button">运行 20 次</button></div></div>
    <div class="v3-grid-2"><div class="v3-pane"><div class="dist-bars"><div class="dist-row"><span>退款进度</span><div class="dist-track"><div class="dist-fill" id="l1DistA"></div></div><b id="l1DistAT">—</b></div><div class="dist-row"><span>投诉</span><div class="dist-track"><div class="dist-fill" id="l1DistB"></div></div><b id="l1DistBT">—</b></div><div class="dist-row"><span>退款申请</span><div class="dist-track"><div class="dist-fill" id="l1DistC"></div></div><b id="l1DistCT">—</b></div></div></div><div class="v3-pane"><div class="v3-metric"><span>格式通过率</span><b id="l1FormatPass">—</b></div><div class="v3-result" id="l1DistExplain">先运行一次。观察“判断更稳定”和“格式更稳定”是不是同一件事。</div></div></div>
  </div>
</div>''','html.parser')
l1_lab_ref.insert_after(l1_dist)

l2 = soup.find(id='lesson2View')
l2_reveal = l2.find(id='l2-reveal')
l2_mix = BeautifulSoup('''
<div class="stage" id="l2ConditionMixer">
  <span class="stage-tag">自由条件混合器</span><h3>项目条件不是固定套餐：自己组合，再看语言选择怎么变</h3>
  <div class="v3-lab"><div class="v3-toolbar"><div><strong>项目条件</strong><small>每开关一个条件，三种语言得分实时变化</small></div><button class="button secondary" id="l2SaveDecision" type="button">保存当前选型</button></div><div class="v3-grid-2"><div class="v3-pane"><div class="condition-grid" id="l2Conditions"></div></div><div class="v3-pane"><div class="dist-bars"><div class="dist-row"><span>Java</span><div class="dist-track"><div class="dist-fill" id="l2MixJava"></div></div><b id="l2MixJavaT"></b></div><div class="dist-row"><span>Python</span><div class="dist-track"><div class="dist-fill" id="l2MixPython"></div></div><b id="l2MixPythonT"></b></div><div class="dist-row"><span>TypeScript</span><div class="dist-track"><div class="dist-fill" id="l2MixTs"></div></div><b id="l2MixTsT"></b></div></div><div class="v3-result" id="l2MixExplain"></div></div></div></div>
</div>''','html.parser')
l2_reveal.insert(2, l2_mix)

l5 = soup.find(id='lesson5View')
l5_reveal = l5.find(id='l5-reveal')
l5_counter = BeautifulSoup('''
<div class="stage" id="l5Counterfactual">
  <span class="stage-tag">反事实删除</span><h3>Prompt 完整以后，再故意删掉一块</h3><p>点击任一块把它关闭。模型结果会立即显示缺少这块的真实后果。</p>
  <div class="counterfactual-grid" id="l5CounterBlocks"><button class="counter-block" data-counter="task" type="button">任务</button><button class="counter-block" data-counter="context" type="button">业务上下文</button><button class="counter-block" data-counter="rules" type="button">判断规则</button><button class="counter-block" data-counter="output" type="button">输出格式</button><button class="counter-block" data-counter="failure" type="button">失败策略</button></div><div class="v3-result" id="l5CounterResult">五块都在：模型知道做什么、按什么规则判断、怎样返回，以及不知道时怎么办。</div>
</div>''','html.parser')
l5_reveal.insert(2, l5_counter)

# New lesson sections
lesson3_html = r'''
<section class="app-view lesson-app" hidden id="lesson3View">
<header class="site-nav"><div class="nav-inner"><a class="brand" data-view="dashboard" href="#"><span class="brand-mark">AI</span><span>第 3 课 · TypeScript 代码修理厂</span></a><div class="nav-scroll"><button class="nav-chip back-dashboard-chip" data-view="dashboard" type="button">← 总控台</button><button class="nav-chip active" data-l3-go="l3-hook" type="button">01 旧经验</button><button class="nav-chip" data-l3-go="l3-lab" type="button">02 修代码</button><button class="nav-chip" data-l3-go="l3-reveal" type="button">03 分清边界</button><button class="nav-chip" data-l3-go="l3-transfer" type="button">04 换题验证</button></div><div class="mastery" id="l3Mastery">掌握 0/4</div></div></header>
<main id="l3-top">
<section class="hero"><div class="eyebrow">TYPESCRIPT REPAIR LAB · LESSON 03</div><h1>Java 转 TypeScript，<span class="marker">不要再装部件，直接修代码</span></h1><p class="hero-lead">这一课只补后续 AI 开发马上会用到的四件事：ESM、await、有限取值和 Zod。你会在一个编辑器里逐个修掉真正的错误。</p><div class="hero-path"><button class="path-step" data-l3-go="l3-hook" type="button"><span>01</span><b>先接旧经验</b><small>Java 对照</small></button><button class="path-step" data-l3-go="l3-lab" type="button"><span>02</span><b>逐个修红线</b><small>编辑并诊断</small></button><button class="path-step" data-l3-go="l3-reveal" type="button"><span>03</span><b>编译期 vs 运行期</b><small>Type 不等于校验</small></button><button class="path-step" data-l3-go="l3-transfer" type="button"><span>04</span><b>换数据验证</b><small>挡住坏返回</small></button></div><p class="hero-note">浏览器内 TypeScript 诊断模拟器 · 支持手动编辑 · 不讲复杂泛型和框架</p></section>
<section class="chapter" id="l3-hook"><div class="chapter-head"><span class="chapter-no">01</span><h2>你已经会大部分编程，缺的是运行方式</h2><span class="chapter-en">Map old knowledge</span></div><p class="chapter-lede">Java 的 import、CompletableFuture、enum、DTO 和 Bean Validation，都能找到接近的 TS 概念。先判断 async 调用会返回什么。</p><div class="stage"><span class="stage-tag">预测门</span><h3><code>async function classify()</code> 被调用时，先拿到什么？</h3><div class="prediction-gate"><div class="prediction-options"><button class="prediction-option" data-l3-pred="object" type="button"><span class="option-key">A</span><span><b>直接得到结果对象</b><small>签名写什么就立刻得到什么</small></span></button><button class="prediction-option" data-l3-pred="promise" type="button"><span class="option-key">B</span><span><b>先得到 Promise</b><small>await 后才拿到真实结果</small></span></button><button class="prediction-option" data-l3-pred="thread" type="button"><span class="option-key">C</span><span><b>自动创建 Java 线程</b><small>async 等于 new Thread</small></span></button></div><div class="gate-result" id="l3PredictionResult">选择一个答案，解锁代码修理厂。</div></div></div></section>
<section class="chapter locked-section" id="l3-lab"><div class="lock-cover"><div class="lock-icon">⌁</div><strong>先完成预测</strong><span>然后从第一条红线开始修。</span></div><div class="chapter-head"><span class="chapter-no">02</span><h2>四条红线，按真实失败顺序修</h2><span class="chapter-en">Edit → diagnose → run</span></div><p class="chapter-lede">可以手动改代码，也可以打开提示。诊断器只检查当前阶段，不会一次把答案全部告诉你。</p><div class="v3-lab"><div class="v3-toolbar"><div><strong>mail-intent-ts</strong><small id="l3StageSubtitle">阶段 1：Node 不知道当前项目使用 ESM</small></div><div class="v3-actions"><button class="button secondary" id="l3Hint" type="button">给我提示</button><button class="button secondary" id="l3Apply" type="button">插入最小修复</button><button class="button primary" id="l3Diagnose" type="button">▶ 运行诊断</button></div></div><div class="code-repair-grid"><aside class="diagnostic-steps" id="l3Steps"></aside><section class="editor-pane"><div class="editor-tabs" id="l3Tabs"></div><textarea class="code-editor" id="l3Editor" spellcheck="false"></textarea></section><aside class="diagnostic-pane"><div class="diagnostic-message" id="l3Diagnostic">运行诊断，查看第一个失败点。</div><div class="hint-box" id="l3HintBox">提示会出现在这里。</div><pre class="test-log" id="l3TestLog">$ npm run start\n等待运行…</pre></aside></div><div class="v3-metrics"><div class="v3-metric"><span>ESM</span><b id="l3M1">○</b></div><div class="v3-metric"><span>await</span><b id="l3M2">○</b></div><div class="v3-metric"><span>有限取值</span><b id="l3M3">○</b></div><div class="v3-metric"><span>运行时校验</span><b id="l3M4">○</b></div></div></div><div class="bridge-artifact"><b>本课产物：</b><span id="l3ArtifactState">修完后保存一份可运行的 TypeScript 调用骨架，下一课直接使用。</span></div></section>
<section class="chapter reveal-locked" id="l3-reveal"><div class="reveal-lock"><strong>完成四条诊断后揭示</strong><span>TypeScript 类型和运行时校验解决的是不同问题。</span></div><div class="chapter-head"><span class="chapter-no">03</span><h2>TypeScript 检查你写的代码，Zod 检查模型真的返回了什么</h2><span class="chapter-en">Compile time vs runtime</span></div><p class="chapter-lede">接口或 type 不能让外部数据自动变真。模型、HTTP 和数据库返回值必须先当作 unknown，再做运行时校验。</p><div class="stage"><div class="runtime-demo"><article class="runtime-card"><h4>编译期</h4><pre><code>type Intent = "refund" | "query";
const x: Intent = "other"; // 红线</code></pre><p>阻止团队在代码里写出不允许的值。</p></article><article class="runtime-card"><h4>运行时</h4><pre><code>const raw: unknown = await callModel();
const parsed = Schema.safeParse(raw);</code></pre><p>阻止模型或接口把错误字段送入业务流程。</p></article></div></div></section>
<section class="chapter" id="l3-transfer"><div class="chapter-head"><span class="chapter-no">04</span><h2><code>as IntentResult</code> 为什么挡不住坏数据？</h2><span class="chapter-en">Transfer challenge</span></div><div class="stage"><span class="stage-tag">选择两个</span><div class="multi-options" id="l3Transfer"><button class="multi-option" data-answer="assert" type="button"><span></span>直接 <code>raw as IntentResult</code></button><button class="multi-option" data-answer="unknown" type="button"><span></span>先把外部返回当作 <code>unknown</code></button><button class="multi-option" data-answer="zod" type="button"><span></span>用 Zod <code>safeParse</code></button><button class="multi-option" data-answer="interface" type="button"><span></span>只声明 interface</button></div><button class="button primary" id="l3CheckTransfer" type="button">检查选择</button><div class="transfer-feedback" id="l3TransferFeedback">请选择两个答案。</div></div><div class="stage"><span class="stage-tag">过关检查</span><div class="quiz" id="l3Quiz"><button class="quiz-option" data-correct="true" type="button">当前目标只是安全发起异步调用并验证返回，所以 ESM、Promise、联合类型和 Zod 已经足够</button><button class="quiz-option" data-correct="false" type="button">因为 TypeScript 没有泛型</button><button class="quiz-option" data-correct="false" type="button">因为 LangChain 必须全部写 any</button><div class="quiz-feedback" id="l3QuizFeedback">选择一个答案。</div></div></div><div class="lesson-bridge"><div><span>下一步</span><h3>参加第 3 课考试</h3><p>通过后，下一课会直接读取你保存的 TS 调用骨架。</p></div><button class="button primary" data-exam="lesson3" disabled id="l3ExamButton" type="button">完成本课后参加考试</button></div></section>
</main><footer class="site-footer"><span>Java 转 AI 应用开发 · Lesson 03</span><span>真实修代码，而不是再装一次部件</span></footer></section>
'''

lesson4_html = r'''
<section class="app-view lesson-app" hidden id="lesson4View"><header class="site-nav"><div class="nav-inner"><a class="brand" data-view="dashboard" href="#"><span class="brand-mark">AI</span><span>第 4 课 · 模型请求与上下文窗口</span></a><div class="nav-scroll"><button class="nav-chip back-dashboard-chip" data-view="dashboard" type="button">← 总控台</button><button class="nav-chip active" data-l4-go="l4-hook" type="button">01 为什么失忆</button><button class="nav-chip" data-l4-go="l4-lab" type="button">02 装请求</button><button class="nav-chip" data-l4-go="l4-reveal" type="button">03 看窗口</button><button class="nav-chip" data-l4-go="l4-transfer" type="button">04 换题验证</button></div><div class="mastery" id="l4Mastery">掌握 0/4</div></div></header><main id="l4-top">
<section class="hero"><div class="eyebrow">MESSAGE WINDOW LAB · LESSON 04</div><h1>你发给模型的，<span class="marker">不只是用户那一句话</span></h1><p class="hero-lead">模型不会自动读取你的数据库，也不会永久记住上一轮。你会亲手把 System、历史、当前问题和业务资料装进一个有限窗口，并看到旧内容如何被挤出去。</p><div class="hero-path"><button class="path-step" data-l4-go="l4-hook" type="button"><span>01</span><b>先看“失忆”</b><small>其实是没收到历史</small></button><button class="path-step" data-l4-go="l4-lab" type="button"><span>02</span><b>装请求包</b><small>有限 Token 预算</small></button><button class="path-step" data-l4-go="l4-reveal" type="button"><span>03</span><b>观察挤出</b><small>输入和输出共用窗口</small></button><button class="path-step" data-l4-go="l4-transfer" type="button"><span>04</span><b>换题验证</b><small>判断缺什么</small></button></div><p class="hero-note">消息传送带 · 上下文窗口 · Token 预算模拟</p></section>
<section class="chapter" id="l4-hook"><div class="chapter-head"><span class="chapter-no">01</span><h2>模型为什么不知道“那个方案”指什么？</h2><span class="chapter-en">No hidden memory</span></div><p class="chapter-lede">因为本次请求只发送了“那个方案什么时候能用？”，没有发送上一轮谈过的“试用期年假方案”。</p><div class="stage"><span class="stage-tag">预测门</span><h3>哪一项最能解决代词不清？</h3><div class="prediction-options"><button class="prediction-option" data-l4-pred="temperature" type="button"><span class="option-key">A</span><span><b>调高 Temperature</b><small>让模型更大胆猜</small></span></button><button class="prediction-option" data-l4-pred="history" type="button"><span class="option-key">B</span><span><b>补回必要历史</b><small>让本次请求包含它所指的对象</small></span></button><button class="prediction-option" data-l4-pred="bigger" type="button"><span class="option-key">C</span><span><b>换更大模型</b><small>希望它凭空知道</small></span></button></div><div class="gate-result" id="l4PredictionResult">选择一个答案，解锁消息窗口。</div></div></section>
<section class="chapter locked-section" id="l4-lab"><div class="lock-cover"><div class="lock-icon">⌁</div><strong>先完成预测</strong><span>再亲手构造一次请求。</span></div><div class="chapter-head"><span class="chapter-no">02</span><h2>把消息和资料放进有限窗口</h2><span class="chapter-en">Build the request</span></div><p class="chapter-lede">左侧选择要发送的内容。右侧调节历史轮数和输出预算；超过总预算时，最早的内容会被标记为“出窗”。</p><div class="v3-lab"><div class="v3-toolbar"><div><strong>请求：那它什么时候能用？</strong><small>总窗口 1600 tokens</small></div><div class="v3-actions"><button class="button secondary" id="l4Clear" type="button">清空</button><button class="button primary" id="l4Run" type="button">▶ 运行模型</button></div></div><div class="message-builder"><aside class="message-shelf" id="l4Shelf"></aside><section class="window-stage"><div class="token-ruler"><div class="token-bar"><div class="token-used" id="l4TokenFill"></div></div><b id="l4TokenText">0 / 1600</b></div><div class="context-controls"><label>历史轮数 <b id="l4TurnsText">2</b><input id="l4Turns" type="range" min="0" max="10" value="2"></label><label>预留输出 Token <b id="l4OutputText">300</b><input id="l4Output" type="range" min="100" max="700" step="50" value="300"></label></div><div class="context-window" id="l4Window"></div><div class="v3-result" id="l4Result">选择 System、当前问题、必要历史和公司制度，然后运行。</div></section></div></div><div class="bridge-artifact"><b>来自上一课：</b><span id="l4PreviousArtifact">正在读取 TypeScript 调用骨架…</span></div></section>
<section class="chapter reveal-locked" id="l4-reveal"><div class="reveal-lock"><strong>成功构造请求后揭示</strong><span>必须让模型理解代词、遵守规则，并保留足够输出空间。</span></div><div class="chapter-head"><span class="chapter-no">03</span><h2>上下文窗口同时装输入和输出</h2><span class="chapter-en">Finite context</span></div><p class="chapter-lede">System、历史、资料和当前问题都占输入 Token；生成回答还需要输出预算。塞得越多不一定越好。</p><div class="stage"><div class="mapping-grid"><article class="mapping-card"><span>SYSTEM</span><h4>告诉模型怎么做</h4><p>角色、规则和不知道时的处理方式。</p></article><article class="mapping-card"><span>HISTORY</span><h4>补回必要对话事实</h4><p>只保留当前问题真正依赖的历史。</p></article><article class="mapping-card"><span>CONTEXT</span><h4>提供业务事实</h4><p>制度、订单或文档不是模型永久记忆。</p></article><article class="mapping-card"><span>OUTPUT BUDGET</span><h4>给回答留空间</h4><p>输入占满窗口，回答可能被截断。</p></article></div></div></section>
<section class="chapter" id="l4-transfer"><div class="chapter-head"><span class="chapter-no">04</span><h2>“继续刚才那个方案”，最先应该补什么？</h2><span class="chapter-en">Transfer challenge</span></div><div class="stage"><div class="quiz" id="l4Quiz"><button class="quiz-option" data-correct="true" type="button">补回能说明“那个方案”指什么的必要历史，而不是把全部聊天都塞进去</button><button class="quiz-option" data-correct="false" type="button">把 Temperature 调到 2</button><button class="quiz-option" data-correct="false" type="button">把 API Key 写进 System Message</button><div class="quiz-feedback" id="l4QuizFeedback">选择一个答案。</div></div></div><div class="lesson-bridge"><div><span>下一步</span><h3>参加第 4 课考试</h3><p>通过后开放第一专栏综合考试。</p></div><button class="button primary" data-exam="lesson4" disabled id="l4ExamButton" type="button">完成本课后参加考试</button></div></section></main><footer class="site-footer"><span>Java 转 AI 应用开发 · Lesson 04</span><span>消息传送带与有限上下文窗口</span></footer></section>
'''

lesson6_html = r'''
<section class="app-view lesson-app" hidden id="lesson6View"><header class="site-nav"><div class="nav-inner"><a class="brand" data-view="dashboard" href="#"><span class="brand-mark">AI</span><span>第 6 课 · 规则路由台</span></a><div class="nav-scroll"><button class="nav-chip back-dashboard-chip" data-view="dashboard" type="button">← 总控台</button><button class="nav-chip active" data-l6-go="l6-hook" type="button">01 看误判</button><button class="nav-chip" data-l6-go="l6-lab" type="button">02 调规则</button><button class="nav-chip" data-l6-go="l6-reveal" type="button">03 说清边界</button><button class="nav-chip" data-l6-go="l6-transfer" type="button">04 换题验证</button></div><div class="mastery" id="l6Mastery">掌握 0/4</div></div></header><main>
<section class="hero"><div class="eyebrow">RULE ROUTING LAB · LESSON 06</div><h1>可执行指令不是写得长，<span class="marker">而是让每个输入有明确去向</span></h1><p class="hero-lead">这一课不再让你“找四张错误卡”。六封邮件会持续流过同一套规则，你可以调整优先级、unknown 出口和边界定义，所有旧案例会立即重跑。</p><div class="hero-path"><button class="path-step" data-l6-go="l6-hook" type="button"><span>01</span><b>先看误判</b><small>边界不清的后果</small></button><button class="path-step" data-l6-go="l6-lab" type="button"><span>02</span><b>调整路由</b><small>规则顺序和出口</small></button><button class="path-step" data-l6-go="l6-reveal" type="button"><span>03</span><b>形成决策表</b><small>可执行而非口号</small></button><button class="path-step" data-l6-go="l6-transfer" type="button"><span>04</span><b>换合同场景</b><small>迁移判断</small></button></div></section>
<section class="chapter" id="l6-hook"><div class="chapter-head"><span class="chapter-no">01</span><h2>“判断邮件类型”为什么还不够？</h2><span class="chapter-en">Ambiguous rules</span></div><div class="stage"><span class="stage-tag">预测门</span><h3>一封邮件既在抱怨，又在问退款何时到账，应该由谁决定优先级？</h3><div class="prediction-options"><button class="prediction-option" data-l6-pred="model" type="button"><span class="option-key">A</span><span><b>让模型按常识决定</b><small>每次自己权衡</small></span></button><button class="prediction-option" data-l6-pred="business" type="button"><span class="option-key">B</span><span><b>由业务规则明确优先级</b><small>模型只执行已声明的边界</small></span></button><button class="prediction-option" data-l6-pred="random" type="button"><span class="option-key">C</span><span><b>随机分一个</b><small>后面再人工修</small></span></button></div><div class="gate-result" id="l6PredictionResult">选择一个答案，解锁规则路由台。</div></div></section>
<section class="chapter locked-section" id="l6-lab"><div class="lock-cover"><div class="lock-icon">⌁</div><strong>先完成预测</strong><span>然后让六封邮件穿过同一套规则。</span></div><div class="chapter-head"><span class="chapter-no">02</span><h2>拖动优先级，所有历史案例立即重跑</h2><span class="chapter-en">Decision table</span></div><div class="v3-lab"><div class="v3-toolbar"><div><strong>客服邮件路由</strong><small>目标：6/6 正确，并且信息不足不乱猜</small></div><div class="v3-actions"><button class="button secondary" id="l6Reset" type="button">恢复默认</button><button class="button primary" id="l6Run" type="button">▶ 运行全部案例</button></div></div><div class="routing-layout"><aside class="rule-panel"><div class="v3-pane-title"><b>规则优先级</b><span>上方先命中</span></div><div id="l6Rules"></div><label class="condition-toggle"><span>允许 unknown 出口</span><input id="l6Unknown" type="checkbox"></label><label class="condition-toggle"><span>到账时间优先于投诉情绪</span><input id="l6ArrivalPriority" type="checkbox"></label><div class="v3-result" id="l6RuleHint">默认规则会误分边界邮件，也会强迫信息不足的输入三选一。</div></aside><section class="routing-stage"><div class="route-flow" id="l6RouteFlow"></div><table class="routing-table"><thead><tr><th>邮件</th><th>期望</th><th>实际</th><th>结果</th></tr></thead><tbody id="l6Rows"></tbody></table></section></div><div class="v3-metrics"><div class="v3-metric"><span>正确率</span><b id="l6Accuracy">—</b></div><div class="v3-metric"><span>边界案例</span><b id="l6Boundary">—</b></div><div class="v3-metric"><span>信息不足</span><b id="l6UnknownMetric">—</b></div><div class="v3-metric"><span>规则冲突</span><b id="l6Conflict">—</b></div></div></div><div class="bridge-artifact"><b>来自第 5 课：</b><span id="l6PromptArtifact">正在读取 Prompt v1…</span></div></section>
<section class="chapter reveal-locked" id="l6-reveal"><div class="reveal-lock"><strong>6/6 正确后揭示</strong><span>可执行规则是一张决策表，而不是一堆漂亮句子。</span></div><div class="chapter-head"><span class="chapter-no">03</span><h2>可执行指令要回答四个问题</h2><span class="chapter-en">Decision boundaries</span></div><div class="stage"><div class="mapping-grid"><article class="mapping-card"><span>LABEL</span><h4>每个类别是什么意思</h4><p>不能只给名字，要给业务定义。</p></article><article class="mapping-card"><span>PRIORITY</span><h4>多意图谁优先</h4><p>把冲突顺序写出来。</p></article><article class="mapping-card"><span>UNKNOWN</span><h4>信息不足怎么办</h4><p>允许合法地说不知道。</p></article><article class="mapping-card"><span>OUTPUT</span><h4>结果如何交给后端</h4><p>下一课会把规则接入 Schema。</p></article></div></div></section>
<section class="chapter" id="l6-transfer"><div class="chapter-head"><span class="chapter-no">04</span><h2>合同风险审核也需要“优先级”和“无法判断”</h2><span class="chapter-en">Transfer challenge</span></div><div class="stage"><div class="quiz" id="l6Quiz"><button class="quiz-option" data-correct="true" type="button">先定义风险类别、冲突优先级和信息不足出口，再让模型判断</button><button class="quiz-option" data-correct="false" type="button">只写“认真审核并详细说明”</button><button class="quiz-option" data-correct="false" type="button">强制模型必须选一个风险等级</button><div class="quiz-feedback" id="l6QuizFeedback">选择一个答案。</div></div></div><div class="lesson-bridge"><div><span>下一步</span><h3>参加第 6 课考试</h3><p>通过后解锁结构化输出与 Zod。</p></div><button class="button primary" data-exam="lesson6" disabled id="l6ExamButton" type="button">完成本课后参加考试</button></div></section></main><footer class="site-footer"><span>Prompt 工程 · Lesson 06</span><span>规则决策台，而不是四张错误卡</span></footer></section>
'''

lesson7_html = r'''
<section class="app-view lesson-app" hidden id="lesson7View"><header class="site-nav"><div class="nav-inner"><a class="brand" data-view="dashboard" href="#"><span class="brand-mark">AI</span><span>第 7 课 · JSON / Zod 检查流水线</span></a><div class="nav-scroll"><button class="nav-chip back-dashboard-chip" data-view="dashboard" type="button">← 总控台</button><button class="nav-chip active" data-l7-go="l7-hook" type="button">01 三层不同</button><button class="nav-chip" data-l7-go="l7-lab" type="button">02 真正编辑</button><button class="nav-chip" data-l7-go="l7-reveal" type="button">03 说清边界</button><button class="nav-chip" data-l7-go="l7-transfer" type="button">04 换题验证</button></div><div class="mastery" id="l7Mastery">掌握 0/4</div></div></header><main>
<section class="hero"><div class="eyebrow">STRUCTURED OUTPUT REPAIR · LESSON 07</div><h1>别只看预设答案，<span class="marker">亲手把坏 JSON 修到可入库</span></h1><p class="hero-lead">左边选择故障，中间直接编辑模型返回，右边是真正执行的三道检查：JSON.parse、Schema 校验和业务规则。</p><div class="hero-path"><button class="path-step" data-l7-go="l7-hook" type="button"><span>01</span><b>先分三层</b><small>语法、Schema、业务</small></button><button class="path-step" data-l7-go="l7-lab" type="button"><span>02</span><b>编辑真实数据</b><small>定位具体字段</small></button><button class="path-step" data-l7-go="l7-reveal" type="button"><span>03</span><b>形成流水线</b><small>外部数据不可信</small></button><button class="path-step" data-l7-go="l7-transfer" type="button"><span>04</span><b>换订单场景</b><small>业务组合判断</small></button></div></section>
<section class="chapter" id="l7-hook"><div class="chapter-head"><span class="chapter-no">01</span><h2>JSON 能解析，不代表字段对；字段对，也不代表业务合理</h2><span class="chapter-en">Three independent gates</span></div><div class="stage"><span class="stage-tag">预测门</span><h3><code>{"intent":"unknown","confidence":0.98}</code> 最大的问题属于哪一层？</h3><div class="prediction-options"><button class="prediction-option" data-l7-pred="json" type="button"><span class="option-key">A</span><span><b>JSON 语法</b><small>它根本不能解析</small></span></button><button class="prediction-option" data-l7-pred="schema" type="button"><span class="option-key">B</span><span><b>字段类型</b><small>confidence 不是数字</small></span></button><button class="prediction-option" data-l7-pred="business" type="button"><span class="option-key">C</span><span><b>业务组合</b><small>unknown 却极高置信度</small></span></button></div><div class="gate-result" id="l7PredictionResult">选择一个答案，解锁 JSON 修理厂。</div></div></section>
<section class="chapter locked-section" id="l7-lab"><div class="lock-cover"><div class="lock-icon">⌁</div><strong>先完成预测</strong><span>然后逐关修复真实数据。</span></div><div class="chapter-head"><span class="chapter-no">02</span><h2>编辑 JSON，让三个故障样例分别通过全部检查</h2><span class="chapter-en">Edit and validate</span></div><div class="v3-lab"><div class="v3-toolbar"><div><strong>AI DTO 修理厂</strong><small>每修好一个故障，进入下一个更深层的问题</small></div><div class="v3-actions"><button class="button secondary" id="l7Reset" type="button">重置当前</button><button class="button primary" id="l7Run" type="button">▶ 运行三层检查</button></div></div><div class="json-lab-grid"><aside class="json-presets" id="l7Presets"></aside><textarea class="json-editor" id="l7Editor" spellcheck="false"></textarea><aside class="gate-stack"><div class="gate-box" id="l7GateJson"><b>1. JSON.parse</b><small>还没运行</small></div><div class="gate-box" id="l7GateSchema"><b>2. Zod Schema</b><small>还没运行</small></div><div class="gate-box" id="l7GateBusiness"><b>3. 业务规则</b><small>还没运行</small></div><div class="v3-result" id="l7Result">从“Markdown 包裹”开始修。</div></aside></div><div class="v3-metrics"><div class="v3-metric"><span>语法故障</span><b id="l7M1">○</b></div><div class="v3-metric"><span>类型故障</span><b id="l7M2">○</b></div><div class="v3-metric"><span>业务故障</span><b id="l7M3">○</b></div><div class="v3-metric"><span>合法样例</span><b id="l7M4">○</b></div></div></div><div class="bridge-artifact"><b>来自第 6 课：</b><span id="l7RulesArtifact">正在读取分类规则…</span></div></section>
<section class="chapter reveal-locked" id="l7-reveal"><div class="reveal-lock"><strong>三个故障全部修好后揭示</strong><span>每一道门都必须给出独立、可解释的失败原因。</span></div><div class="chapter-head"><span class="chapter-no">03</span><h2>安全边界：unknown → parse → schema → business</h2><span class="chapter-en">Validation pipeline</span></div><div class="stage"><div class="concept-equation"><button class="equation-term"><span>unknown</span><small>外部原始数据</small></button><span class="equation-op">→</span><button class="equation-term"><span>JSON</span><small>语法合法</small></button><span class="equation-op">→</span><button class="equation-term"><span>Zod</span><small>字段与类型</small></button><span class="equation-op">→</span><button class="equation-term result-term"><span>Domain</span><small>业务组合合理</small></button></div></div></section>
<section class="chapter" id="l7-transfer"><div class="chapter-head"><span class="chapter-no">04</span><h2>订单金额是负数，属于哪一层？</h2><span class="chapter-en">Transfer challenge</span></div><div class="stage"><div class="quiz" id="l7Quiz"><button class="quiz-option" data-correct="true" type="button">字段是 number 可能通过 Schema，但金额不能为负属于业务规则</button><button class="quiz-option" data-correct="false" type="button">只要 JSON.parse 成功就可以写库</button><button class="quiz-option" data-correct="false" type="button">用 as 强转即可</button><div class="quiz-feedback" id="l7QuizFeedback">选择一个答案。</div></div></div><div class="lesson-bridge"><div><span>下一步</span><h3>参加第 7 课考试</h3><p>通过后解锁 Few-shot 示例设计。</p></div><button class="button primary" data-exam="lesson7" disabled id="l7ExamButton" type="button">完成本课后参加考试</button></div></section></main><footer class="site-footer"><span>Prompt 工程 · Lesson 07</span><span>真正编辑 JSON，而不是只看四个预设</span></footer></section>
'''

lesson8_html = r'''
<section class="app-view lesson-app" hidden id="lesson8View"><header class="site-nav"><div class="nav-inner"><a class="brand" data-view="dashboard" href="#"><span class="brand-mark">AI</span><span>第 8 课 · Few-shot 语义地图</span></a><div class="nav-scroll"><button class="nav-chip back-dashboard-chip" data-view="dashboard" type="button">← 总控台</button><button class="nav-chip active" data-l8-go="l8-hook" type="button">01 不是训练</button><button class="nav-chip" data-l8-go="l8-lab" type="button">02 选示例</button><button class="nav-chip" data-l8-go="l8-reveal" type="button">03 看覆盖</button><button class="nav-chip" data-l8-go="l8-transfer" type="button">04 换题验证</button></div><div class="mastery" id="l8Mastery">掌握 0/4</div></div></header><main>
<section class="hero"><div class="eyebrow">FEW-SHOT SEMANTIC MAP · LESSON 08</div><h1>预算只够三个例子，<span class="marker">不要选三个几乎一样的</span></h1><p class="hero-lead">当前邮件在地图中央。距离近表示相关，但两个例子挤在一起也可能只是重复。你需要同时考虑相关性、边界覆盖和失败出口。</p><div class="hero-path"><button class="path-step" data-l8-go="l8-hook" type="button"><span>01</span><b>先拆误区</b><small>示例不会改权重</small></button><button class="path-step" data-l8-go="l8-lab" type="button"><span>02</span><b>在地图选例子</b><small>有限 Token 预算</small></button><button class="path-step" data-l8-go="l8-reveal" type="button"><span>03</span><b>看相关与多样</b><small>不只追最近</small></button><button class="path-step" data-l8-go="l8-transfer" type="button"><span>04</span><b>换合同场景</b><small>迁移判断</small></button></div></section>
<section class="chapter" id="l8-hook"><div class="chapter-head"><span class="chapter-no">01</span><h2>Few-shot 是本次 Prompt 的例子，不是重新训练模型</h2><span class="chapter-en">Examples in context</span></div><div class="stage"><span class="stage-tag">预测门</span><h3>加入三个示例以后，模型权重会被永久修改吗？</h3><div class="prediction-options"><button class="prediction-option" data-l8-pred="yes" type="button"><span class="option-key">A</span><span><b>会</b><small>示例等于在线训练</small></span></button><button class="prediction-option" data-l8-pred="no" type="button"><span class="option-key">B</span><span><b>不会</b><small>示例只是本次上下文的一部分</small></span></button><button class="prediction-option" data-l8-pred="db" type="button"><span class="option-key">C</span><span><b>只修改数据库</b><small>和模型无关</small></span></button></div><div class="gate-result" id="l8PredictionResult">选择一个答案，解锁语义地图。</div></div></section>
<section class="chapter locked-section" id="l8-lab"><div class="lock-cover"><div class="lock-icon">⌁</div><strong>先完成预测</strong><span>然后在地图中选择三个示例。</span></div><div class="chapter-head"><span class="chapter-no">02</span><h2>离当前问题近，还要避免重复并覆盖失败场景</h2><span class="chapter-en">Relevance + diversity</span></div><div class="v3-lab"><div class="v3-toolbar"><div><strong>当前邮件：退款为什么还没到账？</strong><small>预算 300 tokens · 最多选择 3 个示例</small></div><div class="v3-actions"><button class="button secondary" id="l8Reset" type="button">重新选择</button><button class="button primary" id="l8Run" type="button">检查示例集</button></div></div><div class="semantic-layout"><div class="semantic-map" id="l8Map"><div class="semantic-axis-x"></div><div class="semantic-axis-y"></div></div><aside class="semantic-side"><div class="budget-line"><span>Token 预算</span><b id="l8Budget">0 / 300</b></div><div class="coverage-list"><div class="coverage-item" id="l8Rel">相关性：—</div><div class="coverage-item" id="l8Div">多样性：—</div><div class="coverage-item" id="l8Boundary">边界例：—</div><div class="coverage-item" id="l8Failure">失败出口：—</div></div><div class="v3-result" id="l8Result">点击地图中的示例。圆形是普通例，虚线是边界例，方形是失败例。</div></aside></div></div><div class="bridge-artifact"><b>来自第 7 课：</b><span id="l8SchemaArtifact">正在读取 Zod Schema…</span></div></section>
<section class="chapter reveal-locked" id="l8-reveal"><div class="reveal-lock"><strong>选出高价值示例集后揭示</strong><span>相关、覆盖和多样性要同时考虑。</span></div><div class="chapter-head"><span class="chapter-no">03</span><h2>最近的三个例子，不一定是最好的三个</h2><span class="chapter-en">Coverage matters</span></div><div class="stage"><div class="mapping-grid"><article class="mapping-card"><span>RELEVANCE</span><h4>和当前输入相关</h4><p>示例必须接近当前边界。</p></article><article class="mapping-card"><span>DIVERSITY</span><h4>不要全部重复</h4><p>三个几乎相同的简单例浪费预算。</p></article><article class="mapping-card"><span>BOUNDARY</span><h4>展示容易混淆处</h4><p>告诉模型为什么不是另一个类别。</p></article><article class="mapping-card"><span>FAILURE</span><h4>展示 unknown</h4><p>信息不足时不要强制猜测。</p></article></div></div></section>
<section class="chapter" id="l8-transfer"><div class="chapter-head"><span class="chapter-no">04</span><h2>合同抽取的三个示例，应该覆盖什么？</h2><span class="chapter-en">Transfer challenge</span></div><div class="stage"><div class="quiz" id="l8Quiz"><button class="quiz-option" data-correct="true" type="button">一个正常合同、一个缺失关键字段、一个条款含糊的边界案例</button><button class="quiz-option" data-correct="false" type="button">三个字段完整、格式几乎一样的合同</button><button class="quiz-option" data-correct="false" type="button">随便选最长的三个例子</button><div class="quiz-feedback" id="l8QuizFeedback">选择一个答案。</div></div></div><div class="lesson-bridge"><div><span>下一步</span><h3>参加第 8 课考试</h3><p>通过后解锁 Prompt 评估与回归。</p></div><button class="button primary" data-exam="lesson8" disabled id="l8ExamButton" type="button">完成本课后参加考试</button></div></section></main><footer class="site-footer"><span>Prompt 工程 · Lesson 08</span><span>语义地图 + Token 预算，而不是卡片三选一</span></footer></section>
'''

lesson9_html = r'''
<section class="app-view lesson-app" hidden id="lesson9View"><header class="site-nav"><div class="nav-inner"><a class="brand" data-view="dashboard" href="#"><span class="brand-mark">AI</span><span>第 9 课 · Prompt 评估矩阵</span></a><div class="nav-scroll"><button class="nav-chip back-dashboard-chip" data-view="dashboard" type="button">← 总控台</button><button class="nav-chip active" data-l9-go="l9-hook" type="button">01 为什么回归</button><button class="nav-chip" data-l9-go="l9-lab" type="button">02 改并重跑</button><button class="nav-chip" data-l9-go="l9-reveal" type="button">03 看指标</button><button class="nav-chip" data-l9-go="l9-transfer" type="button">04 发布判断</button></div><div class="mastery" id="l9Mastery">掌握 0/4</div></div></header><main>
<section class="hero"><div class="eyebrow">PROMPT EVALUATION MATRIX · LESSON 09</div><h1>Prompt 改了一句话，<span class="marker">别只试一个成功案例</span></h1><p class="hero-lead">你可以直接修改 Prompt、运行同一组 Golden Dataset、筛选回归案例，并把新发现的边界输入加入测试集。</p><div class="hero-path"><button class="path-step" data-l9-go="l9-hook" type="button"><span>01</span><b>先拆误区</b><small>单个成功案例不够</small></button><button class="path-step" data-l9-go="l9-lab" type="button"><span>02</span><b>改一行再重跑</b><small>评估矩阵</small></button><button class="path-step" data-l9-go="l9-reveal" type="button"><span>03</span><b>看回归而非平均</b><small>关键案例优先</small></button><button class="path-step" data-l9-go="l9-transfer" type="button"><span>04</span><b>判断能否发布</b><small>版本与回退</small></button></div></section>
<section class="chapter" id="l9-hook"><div class="chapter-head"><span class="chapter-no">01</span><h2>Prompt v2 平均分更高，就一定可以发布吗？</h2><span class="chapter-en">Average can hide regressions</span></div><div class="stage"><span class="stage-tag">预测门</span><div class="prediction-options"><button class="prediction-option" data-l9-pred="yes" type="button"><span class="option-key">A</span><span><b>可以</b><small>平均分提高就说明全面变好</small></span></button><button class="prediction-option" data-l9-pred="dataset" type="button"><span class="option-key">B</span><span><b>不一定</b><small>还要检查关键案例是否回归</small></span></button><button class="prediction-option" data-l9-pred="length" type="button"><span class="option-key">C</span><span><b>看 Prompt 长度</b><small>越长越可靠</small></span></button></div><div class="gate-result" id="l9PredictionResult">选择一个答案，解锁评估矩阵。</div></div></section>
<section class="chapter locked-section" id="l9-lab"><div class="lock-cover"><div class="lock-icon">⌁</div><strong>先完成预测</strong><span>然后修改 Prompt 并重跑固定测试集。</span></div><div class="chapter-head"><span class="chapter-no">02</span><h2>修改一行规则，观察修复和新回归</h2><span class="chapter-en">Edit → evaluate → inspect</span></div><div class="v3-lab"><div class="v3-toolbar"><div><strong>Prompt v2 编辑器</strong><small>同一 Dataset、同一 evaluator，比较才有意义</small></div><div class="v3-actions"><button class="button secondary eval-filter" id="l9Filter" type="button">只看失败/回归</button><button class="button primary" id="l9Run" type="button">▶ 运行评估</button></div></div><div class="eval-controls"><div class="prompt-editor-wrap"><textarea class="prompt-editor" id="l9Prompt"></textarea><div class="golden-add"><input id="l9NewInput" placeholder="新增边界输入"><input id="l9NewExpected" placeholder="期望标签"><button class="button secondary" id="l9AddCase" type="button">加入 Golden Set</button></div></div><aside class="eval-side"><div class="v3-metric"><span>准确率</span><b id="l9Accuracy">—</b></div><div class="v3-metric"><span>Schema 通过率</span><b id="l9SchemaRate">—</b></div><div class="v3-metric"><span>回归数量</span><b id="l9Regression">—</b></div><div class="v3-result" id="l9Explain">先运行。默认 v2 修复两个边界，但错误拒绝“缺订单号的退款申请”。</div></aside></div><div class="eval-table-wrap"><table class="eval-table-v3"><thead><tr><th>案例</th><th>期望</th><th>v1</th><th>当前 Prompt</th><th>状态</th></tr></thead><tbody id="l9Rows"></tbody></table></div></div><div class="bridge-artifact"><b>来自第 8 课：</b><span id="l9FewShotArtifact">正在读取 Few-shot 示例集…</span></div></section>
<section class="chapter reveal-locked" id="l9-reveal"><div class="reveal-lock"><strong>修复回归并达到全量通过后揭示</strong><span>平均分、关键案例和版本记录必须同时存在。</span></div><div class="chapter-head"><span class="chapter-no">03</span><h2>Prompt 应像代码一样有版本、数据集和回归报告</h2><span class="chapter-en">Dataset + target + evaluator</span></div><div class="stage"><div class="mapping-grid"><article class="mapping-card"><span>DATASET</span><h4>固定输入和期望</h4><p>让版本比较可重复。</p></article><article class="mapping-card"><span>TARGET</span><h4>被测试的 Prompt/应用</h4><p>保留版本，必要时回退。</p></article><article class="mapping-card"><span>EVALUATOR</span><h4>明确通过标准</h4><p>标签、Schema 和业务规则都可测。</p></article><article class="mapping-card"><span>REGRESSION</span><h4>重点检查旧能力</h4><p>平均分不能掩盖关键失败。</p></article></div></div></section>
<section class="chapter" id="l9-transfer"><div class="chapter-head"><span class="chapter-no">04</span><h2>发布 Prompt v3 前，哪套流程更可靠？</h2><span class="chapter-en">Release decision</span></div><div class="stage"><div class="quiz" id="l9Quiz"><button class="quiz-option" data-correct="true" type="button">保留 v2，v3 跑同一测试集；检查关键回归，通过后再发布并保留回退能力</button><button class="quiz-option" data-correct="false" type="button">只测最新发现的一条成功案例</button><button class="quiz-option" data-correct="false" type="button">Prompt 更长就直接覆盖旧版本</button><div class="quiz-feedback" id="l9QuizFeedback">选择一个答案。</div></div></div><div class="lesson-bridge"><div><span>下一步</span><h3>参加第 9 课考试</h3><p>通过后开放第二专栏综合考试。</p></div><button class="button primary" data-exam="lesson9" disabled id="l9ExamButton" type="button">完成本课后参加考试</button></div></section></main><footer class="site-footer"><span>Prompt 工程 · Lesson 09</span><span>可修改、可重跑、可筛回归</span></footer></section>
'''

for lesson_id, html in [(3,lesson3_html),(4,lesson4_html),(6,lesson6_html),(7,lesson7_html),(8,lesson8_html),(9,lesson9_html)]:
    old = soup.find(id=f'lesson{lesson_id}View')
    old.replace_with(BeautifulSoup(html, 'html.parser'))

# Artifact store script
artifact_script = r'''
(() => {
  'use strict';
  const KEY='ai-academy-artifacts-v3';
  const safeRead=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
  const safeWrite=data=>{try{localStorage.setItem(KEY,JSON.stringify(data))}catch{};window.__academyArtifacts=data;document.dispatchEvent(new CustomEvent('academy-artifact-change',{detail:data}))};
  window.AcademyArtifacts={
    get(name){const d=window.__academyArtifacts||safeRead();return name?d[name]:d},
    set(name,value){const d={...(window.__academyArtifacts||safeRead()),[name]:value};safeWrite(d);return value},
    merge(patch){const d={...(window.__academyArtifacts||safeRead()),...patch};safeWrite(d);return d},
    reset(){safeWrite({})}
  };
  window.__academyArtifacts=safeRead();
})();
'''
first_script = soup.find('script')
new_script_tag = soup.new_tag('script')
new_script_tag.string = artifact_script
first_script.insert_before(new_script_tag)

# Replacement scripts
script3 = r'''
(() => {'use strict';
const root=document.getElementById('lesson3View'),$=(s)=>root.querySelector(s),$$=(s)=>[...root.querySelectorAll(s)];
const set=(k,v)=>{window.__academyMemory=window.__academyMemory||{};window.__academyMemory[k]=v;try{localStorage.setItem(k,v)}catch{}};
const stages=[
 {id:'esm',title:'ESM 模块',file:'package.json',sub:'阶段 1：Node 不知道当前项目使用 ESM',code:'{\n  "name": "mail-intent-ts",\n  "scripts": { "start": "tsx src/index.ts" }\n}',hint:'在 package.json 顶层加入 "type": "module"。',fix:'{\n  "name": "mail-intent-ts",\n  "type": "module",\n  "scripts": { "start": "tsx src/index.ts" }\n}',check:c=>/"type"\s*:\s*"module"/.test(c),fail:'ERR_UNKNOWN_FILE_EXTENSION：项目没有声明 ESM。'},
 {id:'await',title:'等待 Promise',file:'src/index.ts',sub:'阶段 2：你在 Promise 上读取 intent',code:'async function classify(email: string) {\n  return { intent: "refund" };\n}\n\nconst result = classify(email);\nconsole.log(result.intent);',hint:'classify 是 async 函数。调用位置需要 await，并把顶层执行放进 async main。',fix:'async function classify(email: string) {\n  return { intent: "refund" };\n}\n\nasync function main() {\n  const result = await classify(email);\n  console.log(result.intent);\n}\nmain();',check:c=>/await\s+classify\(/.test(c),fail:'TS2339：Promise 上不存在 intent。'},
 {id:'types',title:'有限取值',file:'src/schema.ts',sub:'阶段 3：intent 仍然允许任意字符串',code:'type Intent = string;\n\nconst result: { intent: Intent } = {\n  intent: "anything"\n};',hint:'把 Intent 改成字符串联合类型，只允许 refund / query / unknown。',fix:'type Intent = "refund" | "query" | "unknown";\n\nconst result: { intent: Intent } = {\n  intent: "refund"\n};',check:c=>/["']refund["']\s*\|\s*["']query["']\s*\|\s*["']unknown["']/.test(c),fail:'类型过宽：编译器无法阻止非法 intent。'},
 {id:'zod',title:'运行时校验',file:'src/schema.ts',sub:'阶段 4：模型真实返回 confidence: "high"',code:'interface IntentResult {\n  intent: "refund" | "query" | "unknown";\n  confidence: number;\n}\n\nconst raw = await callModel(email);\nconst result = raw as IntentResult;\nreturn result;',hint:'把 raw 当作 unknown，用 Zod Schema.safeParse 检查真实字段。',fix:'const IntentResult = z.object({\n  intent: z.enum(["refund", "query", "unknown"]),\n  confidence: z.number().min(0).max(1)\n});\n\nconst raw: unknown = await callModel(email);\nconst parsed = IntentResult.safeParse(raw);\nif (!parsed.success) return { intent: "unknown", confidence: 0 };\nreturn parsed.data;',check:c=>/unknown/.test(c)&&/safeParse\s*\(/.test(c)&&/z\.object/.test(c),fail:'运行时风险：as 只告诉编译器“相信我”，不会检查真实数据。'}
];
let stage=0,progress=new Set(),transfer=new Set();
function mark(k){progress.add(k);$('#l3Mastery').textContent=`掌握 ${progress.size}/4${progress.size>=4?' ✓':''}`;if(['lab','transfer','quiz'].every(x=>progress.has(x))){set('ai-academy-l3-content','true');$('#l3ExamButton').disabled=false;$('#l3ExamButton').textContent='参加第 3 课考试'}}
$$('[data-l3-go]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.l3Go)?.scrollIntoView({behavior:'smooth'}));
$$('[data-l3-pred]').forEach(b=>b.onclick=()=>{if($('#l3-lab').classList.contains('unlocked'))return;$$('[data-l3-pred]').forEach(x=>{x.disabled=true;x.classList.toggle('selected',x===b)});const ok=b.dataset.l3Pred==='promise';$('#l3PredictionResult').className=`gate-result ${ok?'good':'miss'}`;$('#l3PredictionResult').textContent=ok?'✓ 对。async 函数先返回 Promise。':'答案已记录。下面直接看诊断器如何报错。';$('#l3-lab').classList.add('unlocked');renderStage()});
function renderSteps(){ $('#l3Steps').innerHTML=stages.map((s,i)=>`<button class="diag-step ${i===stage?'active':''} ${i<stage?'done':''}" type="button" disabled><i>${i<stage?'✓':i+1}</i><span><b>${s.title}</b><small>${s.file}</small></span></button>`).join('') }
function renderStage(){const s=stages[Math.min(stage,stages.length-1)];renderSteps();$('#l3StageSubtitle').textContent=s.sub;$('#l3Tabs').innerHTML=`<button class="editor-tab active" type="button">${s.file}</button>`;$('#l3Editor').value=s.code;$('#l3Diagnostic').className='diagnostic-message';$('#l3Diagnostic').textContent='运行诊断，查看当前失败。';$('#l3HintBox').textContent='提示会出现在这里。';$('#l3TestLog').textContent='$ npm run start\n等待运行…';['l3M1','l3M2','l3M3','l3M4'].forEach((id,i)=>$('#'+id).textContent=i<stage?'✓':'○')}
$('#l3Hint').onclick=()=>$('#l3HintBox').textContent=stages[stage]?.hint||'已经全部完成。';
$('#l3Apply').onclick=()=>{if(stage<stages.length)$('#l3Editor').value=stages[stage].fix};
$('#l3Diagnose').onclick=()=>{if(stage>=stages.length)return;const s=stages[stage],code=$('#l3Editor').value;if(!s.check(code)){ $('#l3Diagnostic').className='diagnostic-message bad';$('#l3Diagnostic').textContent=s.fail;$('#l3TestLog').textContent=`$ npm run start\n✗ ${s.fail}`;return } $('#l3Diagnostic').className='diagnostic-message good';$('#l3Diagnostic').textContent='✓ 当前问题已修复。';$('#l3TestLog').textContent=`$ npm run start\n✓ ${s.title} 检查通过`;stage++;if(stage<stages.length)setTimeout(renderStage,350);else{['l3M1','l3M2','l3M3','l3M4'].forEach(id=>$('#'+id).textContent='✓');$('#l3-reveal').classList.add('reveal-unlocked');mark('lab');const source=stages[3].fix;AcademyArtifacts.set('tsSource',{language:'TypeScript',runtime:'Node.js 22+',source,createdAt:new Date().toISOString()});$('#l3ArtifactState').textContent='已保存：TypeScript 调用骨架 + Zod 运行时校验。';setTimeout(()=>$('#l3-reveal').scrollIntoView({behavior:'smooth'}),350)}};
$$('#l3Transfer .multi-option').forEach(b=>b.onclick=()=>{const a=b.dataset.answer;if(transfer.has(a))transfer.delete(a);else{if(transfer.size>=2)return;transfer.add(a)}b.classList.toggle('selected',transfer.has(a))});
$('#l3CheckTransfer').onclick=()=>{if(transfer.size!==2){$('#l3TransferFeedback').textContent='请选择两个答案。';return}const ok=transfer.has('unknown')&&transfer.has('zod');$('#l3TransferFeedback').className=`transfer-feedback ${ok?'good':'bad'}`;if(ok){$('#l3TransferFeedback').textContent='✓ 对。unknown 阻止盲信，safeParse 真正检查数据。';mark('transfer')}else $('#l3TransferFeedback').textContent='as 和 interface 都只影响编译器，可以取消后重选。'};
$$('#l3Quiz .quiz-option').forEach(b=>b.onclick=()=>{const ok=b.dataset.correct==='true';if(ok){$$('#l3Quiz .quiz-option').forEach(x=>x.disabled=true);b.classList.add('correct');$('#l3QuizFeedback').className='quiz-feedback good';$('#l3QuizFeedback').textContent='✓ 对。先学够用的最小工具箱。';mark('quiz')}else{b.classList.add('wrong');$('#l3QuizFeedback').className='quiz-feedback bad';$('#l3QuizFeedback').textContent='还不对，可以继续选择。';setTimeout(()=>b.classList.remove('wrong'),500)}});
})();
'''

script4 = r'''
(() => {'use strict';const root=document.getElementById('lesson4View'),$=s=>root.querySelector(s),$$=s=>[...root.querySelectorAll(s)];const set=(k,v)=>{window.__academyMemory=window.__academyMemory||{};window.__academyMemory[k]=v;try{localStorage.setItem(k,v)}catch{}};let progress=new Set();const items=[{id:'system',label:'System 规则',tokens:180,type:'system',text:'公司制度助手；不知道时不要猜'},{id:'user',label:'当前用户消息',tokens:65,type:'user',text:'那它什么时候能用？'},{id:'history',label:'必要历史',tokens:220,type:'history',text:'上一轮讨论：试用期员工年假方案'},{id:'document',label:'公司制度',tokens:430,type:'document',text:'转正后次月可使用年假'},{id:'irrelevant',label:'无关聊天',tokens:520,type:'history',text:'午饭、天气和其他项目闲聊'}];let selected=new Set(['user']),success=false;
function mark(k){progress.add(k);$('#l4Mastery').textContent=`掌握 ${progress.size}/4${progress.size>=4?' ✓':''}`;if(['lab','quiz'].every(x=>progress.has(x))){set('ai-academy-l4-content','true');$('#l4ExamButton').disabled=false;$('#l4ExamButton').textContent='参加第 4 课考试'}}
$$('[data-l4-go]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.l4Go)?.scrollIntoView({behavior:'smooth'}));$$('[data-l4-pred]').forEach(b=>b.onclick=()=>{if($('#l4-lab').classList.contains('unlocked'))return;$$('[data-l4-pred]').forEach(x=>{x.disabled=true;x.classList.toggle('selected',x===b)});const ok=b.dataset.l4Pred==='history';$('#l4PredictionResult').className=`gate-result ${ok?'good':'miss'}`;$('#l4PredictionResult').textContent=ok?'✓ 对。模型只看本次请求实际包含的内容。':'答案已记录。下面亲手构造本次请求。';$('#l4-lab').classList.add('unlocked');render()});
function renderShelf(){$('#l4Shelf').innerHTML='<div class="v3-pane-title"><b>可发送内容</b><span>点击加入/移除</span></div>'+items.map(i=>`<button class="message-card ${selected.has(i.id)?'selected':''}" data-item="${i.id}" type="button"><b>${i.label}</b><small>${i.tokens} tokens · ${i.text}</small></button>`).join('');$$('[data-item]').forEach(b=>b.onclick=()=>{const id=b.dataset.item;if(id==='user')return;selected.has(id)?selected.delete(id):selected.add(id);render()})}
function buildWindow(){const turns=Number($('#l4Turns').value),output=Number($('#l4Output').value);let dynamic=[];for(let i=0;i<turns;i++)dynamic.push({id:'turn'+i,label:`历史轮 ${i+1}`,tokens:90,type:'history',text:i===0?'用户问过试用期年假':'无关的上一轮闲聊'});let list=[...items.filter(i=>selected.has(i.id)),...dynamic];const totalInput=list.reduce((s,i)=>s+i.tokens,0),limit=1600-output;let overflow=Math.max(0,totalInput-limit),evicted=new Set();for(const i of list){if(overflow<=0)break;if(i.id==='system'||i.id==='user')continue;overflow-=i.tokens;evicted.add(i.id)}const used=totalInput+output;$('#l4TokenText').textContent=`${used} / 1600`;$('#l4TokenFill').style.width=`${Math.min(100,used/16)}%`;$('#l4TokenFill').classList.toggle('warn',used>1600);$('#l4Window').innerHTML=list.map(i=>`<div class="context-item ${i.type} ${evicted.has(i.id)?'evicted':''}"><b>${i.label}</b><br>${i.text}<br><small>${i.tokens} tokens${evicted.has(i.id)?' · 已出窗':''}</small></div>`).join('');return{list,evicted,used,output}}
function render(){renderShelf();$('#l4TurnsText').textContent=$('#l4Turns').value;$('#l4OutputText').textContent=$('#l4Output').value;buildWindow()}
$('#l4Turns').oninput=render;$('#l4Output').oninput=render;$('#l4Clear').onclick=()=>{selected=new Set(['user']);$('#l4Turns').value=0;render()};$('#l4Run').onclick=()=>{const {evicted,used,output}=buildWindow();const has=id=>selected.has(id)&&!evicted.has(id);let msg;if(!has('history'))msg='模型仍不知道“它”指什么：必要历史缺失或已出窗。';else if(!has('system'))msg='模型理解对象了，但没有“不知道时不要猜”的行为规则。';else if(!has('document'))msg='模型知道在问年假，却没有公司制度事实，无法回答何时可用。';else if(selected.has('irrelevant')||used>1600)msg='请求塞入太多无关内容，关键历史被挤出或没有输出空间。';else if(output<250)msg='输入完整，但给回答预留的输出空间太小，可能被截断。';else{msg='✓ 回答：试用期年假方案在转正后的次月可以使用。';success=true;$('#l4-reveal').classList.add('reveal-unlocked');mark('lab');AcademyArtifacts.set('messages',{system:'公司制度助手；不知道时不要猜',history:['上一轮讨论：试用期员工年假方案'],user:'那它什么时候能用？',context:'转正后次月可使用年假',outputBudget:output});setTimeout(()=>$('#l4-reveal').scrollIntoView({behavior:'smooth'}),350)}$('#l4Result').className=`v3-result ${success?'good':'bad'}`;$('#l4Result').textContent=msg};
const prev=AcademyArtifacts.get('tsSource');$('#l4PreviousArtifact').textContent=prev?'已读取：上一课保存的 TypeScript 调用骨架。':'尚未找到产物；不影响本课演示。';$$('#l4Quiz .quiz-option').forEach(b=>b.onclick=()=>{const ok=b.dataset.correct==='true';if(ok){$$('#l4Quiz .quiz-option').forEach(x=>x.disabled=true);b.classList.add('correct');$('#l4QuizFeedback').className='quiz-feedback good';$('#l4QuizFeedback').textContent='✓ 对。只补必要历史，不是把全部聊天都塞进去。';mark('quiz')}else{b.classList.add('wrong');$('#l4QuizFeedback').className='quiz-feedback bad';$('#l4QuizFeedback').textContent='还不对，可以继续选择。';setTimeout(()=>b.classList.remove('wrong'),500)}});render();})();
'''

script6 = r'''
(() => {'use strict';const root=document.getElementById('lesson6View'),$=s=>root.querySelector(s),$$=s=>[...root.querySelectorAll(s)];const set=(k,v)=>{window.__academyMemory=window.__academyMemory||{};window.__academyMemory[k]=v;try{localStorage.setItem(k,v)}catch{}};let progress=new Set(),order=['complaint','refund_query','refund'];const cases=[['退款还没到账，问了三次','refund_query'],['服务态度太差，不涉及退款','complaint'],['我要申请退款','refund'],['帮我处理一下','unknown'],['退款什么时候退，客服也不回','refund_query'],['商品损坏，要求退款','refund']];
function mark(k){progress.add(k);$('#l6Mastery').textContent=`掌握 ${progress.size}/4${progress.size>=4?' ✓':''}`;if(['lab','quiz'].every(x=>progress.has(x))){set('ai-academy-l6-content','true');$('#l6ExamButton').disabled=false;$('#l6ExamButton').textContent='参加第 6 课考试'}}
$$('[data-l6-go]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.l6Go)?.scrollIntoView({behavior:'smooth'}));$$('[data-l6-pred]').forEach(b=>b.onclick=()=>{if($('#l6-lab').classList.contains('unlocked'))return;$$('[data-l6-pred]').forEach(x=>{x.disabled=true;x.classList.toggle('selected',x===b)});const ok=b.dataset.l6Pred==='business';$('#l6PredictionResult').className=`gate-result ${ok?'good':'miss'}`;$('#l6PredictionResult').textContent=ok?'✓ 对。优先级必须来自业务，而不是模型常识。':'答案已记录。下面看规则顺序如何造成真实误路由。';$('#l6-lab').classList.add('unlocked');renderRules();run(false)});
function renderRules(){$('#l6Rules').innerHTML=order.map((r,i)=>`<div class="rule-row"><i>${i+1}</i><b>${{complaint:'检测投诉情绪',refund_query:'检测退款到账/进度',refund:'检测退款申请'}[r]}</b><span class="rule-controls"><button data-up="${i}" type="button">↑</button><button data-down="${i}" type="button">↓</button></span></div>`).join('');$$('[data-up]').forEach(b=>b.onclick=()=>{const i=+b.dataset.up;if(i>0){[order[i-1],order[i]]=[order[i],order[i-1]];renderRules();run(false)}});$$('[data-down]').forEach(b=>b.onclick=()=>{const i=+b.dataset.down;if(i<order.length-1){[order[i+1],order[i]]=[order[i],order[i+1]];renderRules();run(false)}})}
function classify(text){for(const r of order){if(r==='complaint'&&/(太差|不回|问了三次)/.test(text)&&!($('#l6ArrivalPriority').checked&&/(到账|什么时候退)/.test(text)))return'complaint';if(r==='refund_query'&&/(到账|什么时候退|进度)/.test(text))return'refund_query';if(r==='refund'&&/(申请退款|要求退款|商品损坏)/.test(text))return'refund'}return $('#l6Unknown').checked?'unknown':'refund'}
function run(scroll=true){const results=cases.map(([t,e])=>[t,e,classify(t)]),ok=results.filter(x=>x[1]===x[2]).length;$('#l6Rows').innerHTML=results.map(([t,e,a])=>`<tr><td>${t}</td><td>${e}</td><td>${a}</td><td class="${e===a?'pass':'fail'}">${e===a?'✓':'✗'}</td></tr>`).join('');$('#l6Accuracy').textContent=`${ok}/6`;$('#l6Boundary').textContent=results[0][2]==='refund_query'&&results[4][2]==='refund_query'?'PASS':'FAIL';$('#l6UnknownMetric').textContent=results[3][2]==='unknown'?'PASS':'FAIL';$('#l6Conflict').textContent=order[0]==='refund_query'||$('#l6ArrivalPriority').checked?'已声明':'未声明';$('#l6RouteFlow').innerHTML=order.map((r,i)=>`<span class="route-node ${i===0?'active':''}">${i+1}. ${r}</span>`).join('<span>→</span>');if(ok===6){$('#l6-reveal').classList.add('reveal-unlocked');$('#l6RuleHint').className='v3-result good';$('#l6RuleHint').textContent='✓ 六个案例全部正确。规则边界和失败出口已经可执行。';mark('lab');const rules={order:[...order],allowUnknown:$('#l6Unknown').checked,arrivalPriority:$('#l6ArrivalPriority').checked,cases};AcademyArtifacts.set('classificationRules',rules);if(scroll)setTimeout(()=>$('#l6-reveal').scrollIntoView({behavior:'smooth'}),350)}else{$('#l6RuleHint').className='v3-result bad';$('#l6RuleHint').textContent='仍有误路由。尝试把退款进度提前、开启 unknown，并明确到账优先。'}}
$('#l6Run').onclick=()=>run(true);$('#l6Unknown').onchange=()=>run(false);$('#l6ArrivalPriority').onchange=()=>run(false);$('#l6Reset').onclick=()=>{order=['complaint','refund_query','refund'];$('#l6Unknown').checked=false;$('#l6ArrivalPriority').checked=false;renderRules();run(false)};const prompt=AcademyArtifacts.get('promptV1');$('#l6PromptArtifact').textContent=prompt?'已读取 Prompt v1；本课会把它升级成明确的决策规则。':'尚未找到 Prompt v1；不影响演示。';$$('#l6Quiz .quiz-option').forEach(b=>b.onclick=()=>{const ok=b.dataset.correct==='true';if(ok){$$('#l6Quiz .quiz-option').forEach(x=>x.disabled=true);b.classList.add('correct');$('#l6QuizFeedback').className='quiz-feedback good';$('#l6QuizFeedback').textContent='✓ 对。边界、优先级和 unknown 都必须明确。';mark('quiz')}else{b.classList.add('wrong');$('#l6QuizFeedback').className='quiz-feedback bad';$('#l6QuizFeedback').textContent='还不对，可以继续选择。';setTimeout(()=>b.classList.remove('wrong'),500)}});renderRules();})();
'''

script7 = r'''
(() => {'use strict';const root=document.getElementById('lesson7View'),$=s=>root.querySelector(s),$$=s=>[...root.querySelectorAll(s)];const set=(k,v)=>{window.__academyMemory=window.__academyMemory||{};window.__academyMemory[k]=v;try{localStorage.setItem(k,v)}catch{}};let progress=new Set(),index=0,passed=new Set();const tasks=[{id:'syntax',title:'Markdown 包裹',desc:'返回被 ```json 包裹，JSON.parse 失败',value:'```json\n{\n  "intent": "refund_query",\n  "confidence": 0.91,\n  "reason": "询问到账时间"\n}\n```',hint:'删除 Markdown 代码围栏，只保留 JSON 对象。'}, {id:'schema',title:'字段类型错误',desc:'confidence 被返回为字符串',value:'{\n  "intent": "refund_query",\n  "confidence": "high",\n  "reason": "询问到账时间"\n}',hint:'confidence 必须是 0 到 1 之间的数字。'}, {id:'business',title:'业务组合错误',desc:'unknown 却给出 0.98 置信度',value:'{\n  "intent": "unknown",\n  "confidence": 0.98,\n  "reason": "信息不足"\n}',hint:'unknown 时置信度不能高于 0.5。'}];
function mark(k){progress.add(k);$('#l7Mastery').textContent=`掌握 ${progress.size}/4${progress.size>=4?' ✓':''}`;if(['lab','quiz'].every(x=>progress.has(x))){set('ai-academy-l7-content','true');$('#l7ExamButton').disabled=false;$('#l7ExamButton').textContent='参加第 7 课考试'}}
$$('[data-l7-go]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.l7Go)?.scrollIntoView({behavior:'smooth'}));$$('[data-l7-pred]').forEach(b=>b.onclick=()=>{if($('#l7-lab').classList.contains('unlocked'))return;$$('[data-l7-pred]').forEach(x=>{x.disabled=true;x.classList.toggle('selected',x===b)});const ok=b.dataset.l7Pred==='business';$('#l7PredictionResult').className=`gate-result ${ok?'good':'miss'}`;$('#l7PredictionResult').textContent=ok?'✓ 对。语法和类型都合法，问题在业务组合。':'答案已记录。下面让三道门分别给出失败原因。';$('#l7-lab').classList.add('unlocked');render()});
function render(){$('#l7Presets').innerHTML=tasks.map((t,i)=>`<button class="json-preset ${i===index?'active':''}" type="button" disabled><b>${i<index?'✓ ':''}${t.title}</b><small>${t.desc}</small></button>`).join('');$('#l7Editor').value=tasks[index]?.value||'{\n  "intent":"refund_query",\n  "confidence":0.91,\n  "reason":"询问到账时间"\n}';['Json','Schema','Business'].forEach(x=>{$('#l7Gate'+x).className='gate-box';$('small',$('#l7Gate'+x)).textContent='还没运行'});$('#l7Result').textContent=tasks[index]?`当前任务：${tasks[index].hint}`:'全部故障已修复。'}
function setGate(id,ok,msg){const el=$('#'+id);el.className=`gate-box ${ok?'pass':'fail'}`;$('small',el).textContent=msg}
$('#l7Run').onclick=()=>{let obj;try{obj=JSON.parse($('#l7Editor').value);setGate('l7GateJson',true,'JSON 语法通过')}catch(e){setGate('l7GateJson',false,'无法解析：'+e.message.split('\n')[0]);setGate('l7GateSchema',false,'未执行');setGate('l7GateBusiness',false,'未执行');$('#l7Result').className='v3-result bad';$('#l7Result').textContent=tasks[index].hint;return}const schemaOk=['refund','refund_query','complaint','unknown'].includes(obj.intent)&&typeof obj.confidence==='number'&&obj.confidence>=0&&obj.confidence<=1&&typeof obj.reason==='string';setGate('l7GateSchema',schemaOk,schemaOk?'字段、类型、枚举和范围通过':'需要 intent 枚举、0~1 数字 confidence、字符串 reason');if(!schemaOk){setGate('l7GateBusiness',false,'未执行');$('#l7Result').className='v3-result bad';$('#l7Result').textContent=tasks[index].hint;return}const businessOk=!(obj.intent==='unknown'&&obj.confidence>0.5);setGate('l7GateBusiness',businessOk,businessOk?'业务组合合理':'unknown 不能同时极高置信度');if(!businessOk){$('#l7Result').className='v3-result bad';$('#l7Result').textContent=tasks[index].hint;return}passed.add(tasks[index].id);$('#l7Result').className='v3-result good';$('#l7Result').textContent='✓ 当前故障已修复，进入下一层。';index++;['l7M1','l7M2','l7M3'].forEach((id,i)=>$('#'+id).textContent=i<index?'✓':'○');if(index<tasks.length)setTimeout(render,350);else{$('#l7M4').textContent='✓';$('#l7-reveal').classList.add('reveal-unlocked');mark('lab');AcademyArtifacts.set('outputSchema',{intent:['refund','refund_query','complaint','unknown'],confidence:'number 0..1',reason:'string',businessRule:'unknown confidence <= 0.5'});setTimeout(()=>$('#l7-reveal').scrollIntoView({behavior:'smooth'}),350)}};
$('#l7Reset').onclick=render;const rules=AcademyArtifacts.get('classificationRules');$('#l7RulesArtifact').textContent=rules?'已读取：退款进度优先、unknown 出口和规则顺序。':'尚未找到规则产物；不影响演示。';$$('#l7Quiz .quiz-option').forEach(b=>b.onclick=()=>{const ok=b.dataset.correct==='true';if(ok){$$('#l7Quiz .quiz-option').forEach(x=>x.disabled=true);b.classList.add('correct');$('#l7QuizFeedback').className='quiz-feedback good';$('#l7QuizFeedback').textContent='✓ 对。类型正确和业务合理是两层。';mark('quiz')}else{b.classList.add('wrong');$('#l7QuizFeedback').className='quiz-feedback bad';$('#l7QuizFeedback').textContent='还不对，可以继续选择。';setTimeout(()=>b.classList.remove('wrong'),500)}});})();
'''

script8 = r'''
(() => {'use strict';const root=document.getElementById('lesson8View'),$=s=>root.querySelector(s),$$=s=>[...root.querySelectorAll(s)];const set=(k,v)=>{window.__academyMemory=window.__academyMemory||{};window.__academyMemory[k]=v;try{localStorage.setItem(k,v)}catch{}};let progress=new Set(),selected=new Set();const points=[{id:'query',label:'当前邮件',x:50,y:50,tokens:0,kind:'query'},{id:'boundary',label:'不满+问到账',x:58,y:45,tokens:105,kind:'boundary'},{id:'simple1',label:'退款进度查询',x:70,y:38,tokens:90,kind:'normal'},{id:'simple2',label:'退款进度查询②',x:73,y:40,tokens:88,kind:'normal'},{id:'contrast',label:'纯服务投诉',x:31,y:66,tokens:100,kind:'normal'},{id:'failure',label:'信息不足→unknown',x:44,y:78,tokens:92,kind:'failure'},{id:'refund',label:'新申请退款',x:22,y:40,tokens:96,kind:'normal'},{id:'noise',label:'营销邮件',x:14,y:18,tokens:70,kind:'normal'}];
function mark(k){progress.add(k);$('#l8Mastery').textContent=`掌握 ${progress.size}/4${progress.size>=4?' ✓':''}`;if(['lab','quiz'].every(x=>progress.has(x))){set('ai-academy-l8-content','true');$('#l8ExamButton').disabled=false;$('#l8ExamButton').textContent='参加第 8 课考试'}}
$$('[data-l8-go]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.l8Go)?.scrollIntoView({behavior:'smooth'}));$$('[data-l8-pred]').forEach(b=>b.onclick=()=>{if($('#l8-lab').classList.contains('unlocked'))return;$$('[data-l8-pred]').forEach(x=>{x.disabled=true;x.classList.toggle('selected',x===b)});const ok=b.dataset.l8Pred==='no';$('#l8PredictionResult').className=`gate-result ${ok?'good':'miss'}`;$('#l8PredictionResult').textContent=ok?'✓ 对。示例只参与本次上下文，不会永久改权重。':'答案已记录。下面在语义地图里挑示例。';$('#l8-lab').classList.add('unlocked');render()});
function render(){const map=$('#l8Map');map.querySelectorAll('.semantic-point').forEach(x=>x.remove());points.forEach(p=>{const b=document.createElement('button');b.className=`semantic-point ${p.kind} ${selected.has(p.id)?'selected':''}`;b.style.left=p.x+'%';b.style.top=p.y+'%';b.textContent=p.label+(p.tokens?` · ${p.tokens}`:'');b.disabled=p.id==='query';b.onclick=()=>toggle(p);map.appendChild(b)});metrics()}
function toggle(p){if(selected.has(p.id))selected.delete(p.id);else{const used=[...selected].reduce((s,id)=>s+points.find(x=>x.id===id).tokens,0);if(selected.size>=3||used+p.tokens>300)return;selected.add(p.id)}render()}
function metrics(){const arr=[...selected].map(id=>points.find(x=>x.id===id)),used=arr.reduce((s,p)=>s+p.tokens,0);$('#l8Budget').textContent=`${used} / 300`;const rel=arr.length?Math.round(arr.reduce((s,p)=>s+Math.max(0,100-Math.hypot(p.x-50,p.y-50)*3),0)/arr.length):0;let minDist=100;if(arr.length>1)for(let i=0;i<arr.length;i++)for(let j=i+1;j<arr.length;j++)minDist=Math.min(minDist,Math.hypot(arr[i].x-arr[j].x,arr[i].y-arr[j].y));const diversity=arr.length<2?0:Math.min(100,Math.round(minDist*5));const boundary=selected.has('boundary'),failure=selected.has('failure');$('#l8Rel').textContent=`相关性：${rel||'—'}${rel?'%':''}`;$('#l8Div').textContent=`多样性：${diversity||'—'}${diversity?'%':''}`;$('#l8Boundary').textContent=`边界例：${boundary?'已覆盖':'未覆盖'}`;$('#l8Failure').textContent=`失败出口：${failure?'已覆盖':'未覆盖'}`;[$('#l8Boundary'),$('#l8Failure')].forEach(x=>x.classList.toggle('pass',/已覆盖/.test(x.textContent)));return{arr,used,rel,diversity,boundary,failure}}
$('#l8Run').onclick=()=>{const m=metrics(),hasContrast=selected.has('contrast');const ok=selected.size===3&&m.boundary&&m.failure&&hasContrast;if(ok){$('#l8Result').className='v3-result good';$('#l8Result').textContent='✓ 示例集同时覆盖当前边界、对比类别和信息不足出口。';$('#l8-reveal').classList.add('reveal-unlocked');mark('lab');AcademyArtifacts.set('fewShotExamples',m.arr.map(p=>({id:p.id,label:p.label,tokens:p.tokens,kind:p.kind})));setTimeout(()=>$('#l8-reveal').scrollIntoView({behavior:'smooth'}),350)}else{$('#l8Result').className='v3-result bad';$('#l8Result').textContent='还不够：需要“边界例 + 纯投诉对比例 + unknown 失败例”，且不能超过预算。'}};$('#l8Reset').onclick=()=>{selected.clear();render();$('#l8Result').className='v3-result';$('#l8Result').textContent='点击地图中的示例。圆形是普通例，虚线是边界例，方形是失败例。'};const schema=AcademyArtifacts.get('outputSchema');$('#l8SchemaArtifact').textContent=schema?'已读取：intent、confidence、reason 和 unknown 业务规则。':'尚未找到 Schema 产物；不影响演示。';$$('#l8Quiz .quiz-option').forEach(b=>b.onclick=()=>{const ok=b.dataset.correct==='true';if(ok){$$('#l8Quiz .quiz-option').forEach(x=>x.disabled=true);b.classList.add('correct');$('#l8QuizFeedback').className='quiz-feedback good';$('#l8QuizFeedback').textContent='✓ 对。典型、失败和歧义共同覆盖行为边界。';mark('quiz')}else{b.classList.add('wrong');$('#l8QuizFeedback').className='quiz-feedback bad';$('#l8QuizFeedback').textContent='还不对，可以继续选择。';setTimeout(()=>b.classList.remove('wrong'),500)}});})();
'''

script9 = r'''
(() => {'use strict';const root=document.getElementById('lesson9View'),$=s=>root.querySelector(s),$$=s=>[...root.querySelectorAll(s)];const set=(k,v)=>{window.__academyMemory=window.__academyMemory||{};window.__academyMemory[k]=v;try{localStorage.setItem(k,v)}catch{}};let progress=new Set(),filter=false;let cases=[{name:'普通退款申请',text:'我要退款',expected:'refund',v1:'refund'},{name:'询问退款到账',text:'退款什么时候到账',expected:'refund_query',v1:'refund'},{name:'不满+到账查询',text:'问了三次还没到账',expected:'refund_query',v1:'complaint'},{name:'纯服务投诉',text:'客服态度太差',expected:'complaint',v1:'complaint'},{name:'信息不足',text:'帮我处理一下',expected:'unknown',v1:'refund'},{name:'退款缺订单号',text:'我要退款，但没找到订单号',expected:'refund',v1:'refund'},{name:'普通订单查询',text:'查订单状态',expected:'query',v1:'query'},{name:'混合多意图',text:'客服很差，退款何时到账',expected:'refund_query',v1:'complaint'}];
const defaultPrompt=`类别：refund / refund_query / complaint / query / unknown\n规则：询问到账时间优先 refund_query。\n信息不足返回 unknown。\n退款申请缺订单号时返回 unknown。`;
function mark(k){progress.add(k);$('#l9Mastery').textContent=`掌握 ${progress.size}/4${progress.size>=4?' ✓':''}`;if(['lab','quiz'].every(x=>progress.has(x))){set('ai-academy-l9-content','true');$('#l9ExamButton').disabled=false;$('#l9ExamButton').textContent='参加第 9 课考试'}}
$$('[data-l9-go]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.l9Go)?.scrollIntoView({behavior:'smooth'}));$$('[data-l9-pred]').forEach(b=>b.onclick=()=>{if($('#l9-lab').classList.contains('unlocked'))return;$$('[data-l9-pred]').forEach(x=>{x.disabled=true;x.classList.toggle('selected',x===b)});const ok=b.dataset.l9Pred==='dataset';$('#l9PredictionResult').className=`gate-result ${ok?'good':'miss'}`;$('#l9PredictionResult').textContent=ok?'✓ 对。平均分可能掩盖关键回归。':'答案已记录。下面用同一 Dataset 直接比较。';$('#l9-lab').classList.add('unlocked')});
function classify(text,prompt){if(/到账|何时到账/.test(text)&&/到账时间优先/.test(prompt))return'refund_query';if(/客服态度|客服很差/.test(text))return'complaint';if(/订单状态/.test(text))return'query';if(/帮我处理/.test(text)&&/信息不足返回 unknown/.test(prompt))return'unknown';if(/我要退款/.test(text)){if(/没找到订单号/.test(text)&&/缺订单号时返回 unknown/.test(prompt))return'unknown';return'refund'}return'unknown'}
function run(){const p=$('#l9Prompt').value;const rows=cases.map(c=>({...c,current:classify(c.text,p)}));const correct=rows.filter(r=>r.current===r.expected).length,reg=rows.filter(r=>r.v1===r.expected&&r.current!==r.expected).length;$('#l9Accuracy').textContent=`${Math.round(correct/rows.length*100)}%`;$('#l9SchemaRate').textContent='100%';$('#l9Regression').textContent=reg;$('#l9Rows').innerHTML=rows.filter(r=>!filter||r.current!==r.expected||r.v1!==r.expected).map(r=>`<tr class="${r.current===r.expected?'fixed':'regression'}"><td>${r.name}</td><td>${r.expected}</td><td>${r.v1}</td><td>${r.current}</td><td>${r.current===r.expected?'✓':'✗'}</td></tr>`).join('');if(correct===rows.length){$('#l9Explain').className='v3-result good';$('#l9Explain').textContent='✓ 全量案例通过，且没有旧案例回归。可以形成 Prompt v3。';$('#l9-reveal').classList.add('reveal-unlocked');mark('lab');AcademyArtifacts.merge({promptV2:{text:p,version:'v3',createdAt:new Date().toISOString()},evaluationReport:{total:rows.length,accuracy:1,regressions:0,rows},evaluationDataset:cases});setTimeout(()=>$('#l9-reveal').scrollIntoView({behavior:'smooth'}),350)}else{$('#l9Explain').className='v3-result bad';$('#l9Explain').textContent=`当前 ${correct}/${rows.length} 通过，${reg} 个回归。提示：删除“退款申请缺订单号时返回 unknown”，改成缺字段只写进 reason。`}}
$('#l9Run').onclick=run;$('#l9Filter').onclick=()=>{filter=!filter;$('#l9Filter').classList.toggle('on',filter);run()};$('#l9AddCase').onclick=()=>{const text=$('#l9NewInput').value.trim(),expected=$('#l9NewExpected').value.trim();if(!text||!expected)return;cases.push({name:'新增边界例',text,expected,v1:'unknown'});$('#l9NewInput').value='';$('#l9NewExpected').value='';run()};$('#l9Prompt').value=defaultPrompt;const ex=AcademyArtifacts.get('fewShotExamples');$('#l9FewShotArtifact').textContent=ex?`已读取 ${ex.length} 个示例；它们会成为当前 Prompt 的 Few-shot 部分。`:'尚未找到 Few-shot 产物；不影响评估演示。';$$('#l9Quiz .quiz-option').forEach(b=>b.onclick=()=>{const ok=b.dataset.correct==='true';if(ok){$$('#l9Quiz .quiz-option').forEach(x=>x.disabled=true);b.classList.add('correct');$('#l9QuizFeedback').className='quiz-feedback good';$('#l9QuizFeedback').textContent='✓ 对。固定数据集、版本和回退能力缺一不可。';mark('quiz')}else{b.classList.add('wrong');$('#l9QuizFeedback').className='quiz-feedback bad';$('#l9QuizFeedback').textContent='还不对，可以继续选择。';setTimeout(()=>b.classList.remove('wrong'),500)}});})();
'''

# Replace script tags 3,4,7,8,9,10
scripts = soup.find_all('script')
# after adding artifact script, original indices shift by 1: artifact=0, lesson1=1, lesson2=2, lesson3=3 ...
replace_map={3:script3,4:script4,7:script6,8:script7,9:script8,10:script9}
for idx, code in replace_map.items():
    scripts[idx].string = code

# Enhancement script appended after all scripts
enhancement_script = r'''
(() => {'use strict';
const A=window.AcademyArtifacts;
// Lesson 1 repeated-run distribution
const r1=document.getElementById('l1DistRun');if(r1)r1.addEventListener('click',()=>{const rules=document.getElementById('l1DistRules').checked,schema=document.getElementById('l1DistSchema').checked;const vals=rules?[85,10,5]:[48,32,20];['A','B','C'].forEach((x,i)=>{document.getElementById('l1Dist'+x).style.width=vals[i]+'%';document.getElementById('l1Dist'+x+'T').textContent=vals[i]+'%'});document.getElementById('l1FormatPass').textContent=schema?'100%':'55%';document.getElementById('l1DistExplain').className='v3-result good';document.getElementById('l1DistExplain').textContent=rules?'业务规则让分类分布收敛；'+(schema?'Schema 另外让格式稳定。':'但返回格式仍可能变化。'):'没有业务规则时，模型在三个相近类别间摇摆。Schema 即使打开，也只固定格式。';A.set('businessRisk',{task:'email intent',risk:'probabilistic classification',needs:['rules','schema','business validation','fallback'],distribution:vals})});
// Lesson 2 condition mixer
const conditions=[['spring','已有 Spring Boot 系统',{java:28,python:-4,ts:-5}],['javaTeam','团队只熟悉 Java',{java:24,python:-8,ts:-9}],['science','需要科学计算/研究',{java:-5,python:32,ts:-4}],['online','必须浏览器在线运行',{java:-7,python:-3,ts:25}],['shared','前后端共享类型',{java:-2,python:-4,ts:22}],['langchain','课程主线 LangChain JS',{java:-5,python:3,ts:26}],['mcp','开发 MCP Server',{java:4,python:10,ts:18}],['fastAlgo','快速验证算法',{java:-6,python:24,ts:2}]];const box=document.getElementById('l2Conditions');if(box){box.innerHTML=conditions.map(c=>`<label class="condition-toggle"><span>${c[1]}</span><input type="checkbox" data-cond="${c[0]}"></label>`).join('');function renderMix(){let s={java:50,python:50,ts:50};box.querySelectorAll('input:checked').forEach(i=>{const c=conditions.find(x=>x[0]===i.dataset.cond);Object.keys(s).forEach(k=>s[k]+=c[2][k])});Object.keys(s).forEach(k=>s[k]=Math.max(5,Math.min(100,s[k])));[['Java','java'],['Python','python'],['Ts','ts']].forEach(([id,k])=>{document.getElementById('l2Mix'+id).style.width=s[k]+'%';document.getElementById('l2Mix'+id+'T').textContent=s[k]});const winner=Object.entries(s).sort((a,b)=>b[1]-a[1])[0][0];document.getElementById('l2MixExplain').textContent=`当前更匹配：${{java:'Java',python:'Python',ts:'TypeScript'}[winner]}。这不是总榜，只是当前条件的结果。`;return{s,winner,conditions:[...box.querySelectorAll('input:checked')].map(i=>i.dataset.cond)}}box.onchange=renderMix;renderMix();document.getElementById('l2SaveDecision').onclick=()=>{const d=renderMix();A.set('languageDecision',d);document.getElementById('l2MixExplain').className='v3-result good';document.getElementById('l2MixExplain').textContent+=' 已保存到课程产物账本。'}}
// Lesson 5 counterfactual deletion + Prompt artifact
const counter=document.getElementById('l5CounterBlocks');if(counter){const text={task:'删除任务：模型不知道要分类还是摘要。',context:'删除业务上下文：类别含义重新依赖模型常识。',rules:'删除判断规则：边界输入开始摇摆。',output:'删除输出格式：后端重新拿到一段散文。',failure:'删除失败策略：信息不足时模型被迫猜。'};counter.querySelectorAll('[data-counter]').forEach(b=>b.onclick=()=>{b.classList.toggle('off');const off=[...counter.querySelectorAll('.off')].map(x=>x.dataset.counter);document.getElementById('l5CounterResult').className=`v3-result ${off.length?'bad':'good'}`;document.getElementById('l5CounterResult').textContent=off.length?off.map(x=>text[x]).join('\n'):'五块都在：模型知道做什么、按什么规则判断、怎样返回，以及不知道时怎么办。'});document.addEventListener('academy-artifact-change',()=>{}, {once:true});const examButton=document.getElementById('l5ExamButton');if(examButton){const obs=new MutationObserver(()=>{if(!examButton.disabled)A.set('promptV1',{task:'classify email',context:'company definitions',rules:'arrival time => refund_query',output:['intent','confidence','reason'],failure:'unknown when insufficient'})});obs.observe(examButton,{attributes:true,attributeFilter:['disabled']})}}
// Artifact ledger
const artifactDefs=[['businessRisk','第 1 课','业务风险与控制层'],['languageDecision','第 2 课','语言选型条件'],['tsSource','第 3 课','TypeScript 调用骨架'],['messages','第 4 课','完整 Messages 请求'],['promptV1','第 5 课','Prompt v1'],['classificationRules','第 6 课','分类规则与优先级'],['outputSchema','第 7 课','Zod Schema'],['fewShotExamples','第 8 课','Few-shot 示例集'],['evaluationReport','第 9 课','评估与回归报告']];function renderLedger(){const grid=document.getElementById('artifactLedgerGrid');if(!grid)return;grid.innerHTML=artifactDefs.map(([k,l,t])=>{const v=A.get(k);return `<article class="artifact-card ${v?'ready':''}"><span>${l}</span><b>${t}</b><small>${v?'✓ 已生成，将进入后续课程':'尚未生成'}</small></article>`}).join('')}document.addEventListener('academy-artifact-change',renderLedger);document.addEventListener('click',e=>{if(e.target.closest('[data-view="dashboard"]'))setTimeout(renderLedger,80)});document.getElementById('resetAllProgress')?.addEventListener('click',()=>{A.reset();setTimeout(renderLedger,50)});renderLedger();
})();
'''
last_tag = soup.new_tag('script')
last_tag.string = enhancement_script
soup.body.append(last_tag)

# Update title and dashboard wording
soup.title.string='AI 应用开发学院 · 多样交互重做版 V3'
# nav add artifact
nav_scroll=soup.find(id='dashboardView').find(class_='nav-scroll')
newbtn=soup.new_tag('button',attrs={'class':'nav-chip','data-console-go':'artifactLedger','type':'button'})
newbtn.string='课程产物'
nav_scroll.append(newbtn)
# Fix review project text
for h3 in soup.find(id='review').find_all('h3'):
    if '三课依赖关系' in h3.get_text(): h3.string='前两专栏的产物依赖关系'

out = OUTDIR/'index.html'
out.write_text(str(soup),encoding='utf-8')
Path('/mnt/data/ai-app-academy-varied-v3.html').write_text(str(soup),encoding='utf-8')

report='''# V3 多样交互重做说明\n\n## 本轮替换\n\n- 第 3 课：装配工作台 → 可编辑 TypeScript 诊断器\n- 第 4 课：装配工作台 → 消息传送带与上下文窗口溢出\n- 第 6 课：错误卡片 → 可重排规则的邮件路由台\n- 第 7 课：预设结果 → 可编辑 JSON + 三道真实检查\n- 第 8 课：示例卡片 → Few-shot 语义地图 + Token 预算\n- 第 9 课：静态 A/B 表 → 可编辑 Prompt + 可重跑评估矩阵\n\n## 增强\n\n- 第 1 课增加 20 次重复运行分布，区分分类稳定与格式稳定。\n- 第 2 课增加自由项目条件混合器。\n- 第 5 课增加 Prompt 反事实删除实验。\n- 新增 ArtifactStore 与总控台产物账本，逐课保存产物。\n\n## 课程产物流\n\n业务风险 → 语言选型 → TS 源码 → Messages → Prompt v1 → 分类规则 → Schema → Few-shot → 评估报告。\n'''
(OUTDIR/'README.md').write_text(report,encoding='utf-8')

zip_path=Path('/mnt/data/ai-app-academy-varied-v3.zip')
with zipfile.ZipFile(zip_path,'w',zipfile.ZIP_DEFLATED) as z:
    for f in OUTDIR.rglob('*'): z.write(f,f.relative_to(OUTDIR.parent))
print(out)
print(zip_path)
