import assert from 'node:assert/strict';
import fs from 'node:fs';

const dashboard = fs.readFileSync('packages/course-runtime/src/formal-dashboard.js', 'utf8');
const css = fs.readFileSync('apps/runtime-academy/formal-dashboard.css', 'utf8');
const main = fs.readFileSync('apps/runtime-academy/main.js', 'utf8');
const html = fs.readFileSync('apps/runtime-academy/index.html', 'utf8');
const officialColumn = fs.readFileSync('courses/ai-app-engineering/column-03-official.js', 'utf8');
const ragColumn = fs.readFileSync('courses/ai-app-engineering/column-04-rag.js', 'utf8');
const graphColumn = fs.readFileSync('courses/ai-app-engineering/column-05-langgraph.js', 'utf8');
const mcpColumn = fs.readFileSync('courses/ai-app-engineering/column-06-mcp.js', 'utf8');
const enterpriseColumn = fs.readFileSync('courses/ai-app-engineering/column-07-enterprise-service-desk.js', 'utf8');

assert.match(dashboard, /七个专栏，一条完整学习路径/);
assert.match(dashboard, /COLUMN \$\{String\(index \+ 1\)\.padStart\(2, '0'\)\}/);
assert.match(dashboard, /LangGraph v1 官方教学基线/);
assert.match(dashboard, /MCP 协议与 Host 接入基线/);
assert.match(dashboard, /NovaTech Enterprise AI Service Desk/);
assert.match(dashboard, /108 节课程/);
assert.match(dashboard, /renderLangChainVersionBanner/);
assert.match(dashboard, /renderRagResearchBanner/);
assert.match(dashboard, /renderLangGraphVersionBanner/);
assert.match(dashboard, /renderMcpVersionBanner/);
assert.match(dashboard, /renderEnterpriseBanner/);
assert.match(dashboard, /QUALITY REVIEW MODE/);
assert.match(dashboard, /reviewColumnStack|review-column-stack/);
assert.match(dashboard, /课程不存在未开发占位专栏/);
assert.doesNotMatch(dashboard, /futureColumns/);
assert.match(officialColumn, /LangChain JavaScript v1/);
assert.match(ragColumn, /RAG 检索与知识库工程/);
assert.match(graphColumn, /LangGraph 与 Agentic RAG/);
assert.match(mcpColumn, /MCP 协议、工具服务与企业集成/);
assert.match(enterpriseColumn, /企业级 AI 解决方案与生产交付/);
assert.match(dashboard, /formal-stats/);
assert.match(dashboard, /formal-continue-sheet/);
assert.match(css, /grid-template-columns:repeat\(7,minmax\(150px,1fr\)\)/);
assert.match(css, /nth-child\(1\).*translateY\(28px\)/s);
assert.match(css, /nth-child\(6\).*translateY\(5px\)/s);
assert.match(main, /installFormalDashboard\(app\)/);
assert.match(main, /extendWithEnterpriseColumn/);
assert.match(main, /installEnterpriseColumnProduct/);
assert.match(main, /installQualityReviewMode/);
assert.match(html, /formal-dashboard\.css/);
assert.match(html, /enterprise\.css/);

console.log('Formal seven-column completed dashboard and quality review checks passed.');
